'use client';
import {useEffect,useMemo,useState} from 'react';
import {seedPrograma,ProgramaRow} from '@/lib/programa';
const machines=['IP-003','IP-004','IP-002','IP-005','IP-006','EP-010','EP-011','EP-008','EP-007','EP-040','IP-001','ARBURG','IP-032','IP-035','IP-039','EP-038','EP-048','IP-040','IP-034','EP-041'];
type Row=ProgramaRow&{semana?:number;seleccionado?:boolean;secuencia?:number;ciclo?:number|null;pz_ciclo?:number|null};
type Tab='material'|'programacion'|'gantt';
const base=(week:number):Row=>({maquina:'',producto:'',op:'',cantidad:null,estatus:'PENDIENTE',molde:'',prioridad:'MEDIA',observaciones:'',material_virgen:'',virgen_kg:null,lote_virgen:'',reciclado:'',reciclado_kg:null,lote_reciclado:'',pigmento:'',pigmento_kg:null,lote_pigmento:'',semana:week,secuencia:1,ciclo:null,pz_ciclo:null});
const mondayOfISOWeek=(week:number)=>{const jan4=new Date(Date.UTC(2026,0,4));const dow=jan4.getUTCDay()||7;const mon=new Date(jan4);mon.setUTCDate(jan4.getUTCDate()-dow+1+(week-1)*7);return mon};
const fmt=(d:Date)=>d.toLocaleDateString('es-MX',{day:'2-digit',month:'short',timeZone:'UTC'}).replace('.','');
const weekLabel=(w:number)=>{const m=mondayOfISOWeek(w),s=new Date(m);s.setUTCDate(m.getUTCDate()+6);return `${fmt(m)}–${fmt(s)} 2026`};
export default function Page(){
 const [week,setWeek]=useState(39); const [tab,setTab]=useState<Tab>('material'); const [rows,setRows]=useState<Row[]>([]); const [ready,setReady]=useState(false); const [search,setSearch]=useState(''); const [machine,setMachine]=useState(''); const [hoursDay,setHoursDay]=useState(16);
 useEffect(()=>{const raw=localStorage.getItem('anclo-planeacion-v4');if(raw){try{setRows(JSON.parse(raw))}catch{}}else setRows(seedPrograma.map((r,i)=>({...r,id:`seed-${i}`,semana:39,secuencia:1})));setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem('anclo-planeacion-v4',JSON.stringify(rows))},[rows,ready]);
 const wr=useMemo(()=>rows.filter(r=>r.semana===week),[rows,week]);
 const visible=useMemo(()=>wr.filter(r=>(!machine||r.maquina===machine)&&(!search||`${r.op} ${r.producto}`.toLowerCase().includes(search.toLowerCase()))),[wr,machine,search]);
 const update=(id:string,k:keyof Row,v:any)=>setRows(rs=>rs.map(r=>r.id===id?{...r,[k]:v}:r));
 const addRows=(n:number)=>setRows(rs=>[...rs,...Array.from({length:n},(_,i)=>({...base(week),id:crypto.randomUUID(),secuencia:wr.length+i+1}))]);
 const newWeek=()=>{const next=Math.max(week,...rows.map(r=>r.semana||0))+1;setWeek(next);setTab('material')};
 const del=()=>setRows(rs=>rs.filter(r=>!(r.semana===week&&r.seleccionado)));
 const calc=useMemo(()=>{const byM=new Map<string,number>();return wr.map((r,i)=>{const seq=(byM.get(r.maquina)||0)+1;byM.set(r.maquina,seq);const pzh=r.ciclo&&r.pz_ciclo?(3600/r.ciclo)*r.pz_ciclo:null;const hrs=pzh&&r.cantidad?r.cantidad/pzh:null;return {...r,_seq:seq,_pzh:pzh,_hrs:hrs,_idx:i}})},[wr]);
 return <><div className="top"><div><div className="title">Planeación semanal</div><div className="muted">Semana {week} · {weekLabel(week)}</div></div></div>
 <div className="weekbar"><button onClick={()=>setWeek(w=>Math.max(1,w-1))}>‹</button><div><b>SEMANA {week}</b><span>{weekLabel(week)}</span></div><button onClick={()=>setWeek(w=>w+1)}>›</button><button className="btn" onClick={newWeek}>+ Nueva semana</button></div>
 <div className="planning-tabs"><button className={tab==='material'?'active':''} onClick={()=>setTab('material')}><b>1</b><span><strong>Material / Programa recibido</strong><small>Captura de partidas y materiales</small></span></button><button className={tab==='programacion'?'active':''} onClick={()=>setTab('programacion')}><b>2</b><span><strong>Programación rápida</strong><small>Secuencia, tiempos y disponibilidad</small></span></button><button className={tab==='gantt'?'active':''} onClick={()=>setTab('gantt')}><b>3</b><span><strong>Gantt preliminar</strong><small>Visualización de la programación</small></span></button></div>
 {tab==='material'&&<Material rows={visible} machines={machines} update={update} addRows={addRows} del={del} search={search} setSearch={setSearch} machine={machine} setMachine={setMachine}/>} 
 {tab==='programacion'&&<Programacion rows={calc} machines={machines} update={update} hoursDay={hoursDay} setHoursDay={setHoursDay}/>} 
 {tab==='gantt'&&<Gantt rows={calc}/>} </>}
function Material({rows,machines,update,addRows,del,search,setSearch,machine,setMachine}:any){return <section className="section"><div className="quick-toolbar"><div className="filters"><input placeholder="🔎 Buscar OP o producto" value={search} onChange={(e:any)=>setSearch(e.target.value)}/><select value={machine} onChange={(e:any)=>setMachine(e.target.value)}><option value="">Todas las máquinas</option>{machines.map((m:string)=><option key={m}>{m}</option>)}</select></div><div className="actions"><button className="btn secondary" onClick={()=>addRows(1)}>+ Fila</button><button className="btn secondary" onClick={()=>addRows(10)}>+ 10 filas</button><button className="btn secondary" onClick={del}>Eliminar seleccionadas</button></div></div><div className="table-wrap grouped-wrap"><table className="quick-table"><thead><tr className="group-head"><th></th><th colSpan={4} className="grp order">🏭 ORDEN / PRODUCTO</th><th colSpan={2} className="grp virgin">🧱 MATERIA PRIMA VIRGEN</th><th colSpan={2} className="grp recycle">♻️ RECICLADO</th><th colSpan={3} className="grp pigment">🎨 PIGMENTO</th><th className="grp plan">MOLDE</th></tr><tr><th>✓</th><th>Máquina</th><th>OP</th><th>Producto / Clave</th><th>Pzas</th><th>kg</th><th>Lote</th><th>kg</th><th>Lote</th><th>Color / Material</th><th>kg</th><th>Lote</th><th>Molde</th></tr></thead><tbody>{rows.map((r:Row)=><tr key={r.id}><td><input type="checkbox" checked={!!r.seleccionado} onChange={e=>update(r.id,'seleccionado',e.target.checked)}/></td><td><select className="cell" value={r.maquina} onChange={e=>update(r.id,'maquina',e.target.value)}><option value="">—</option>{machines.map((m:string)=><option key={m}>{m}</option>)}</select></td><C r={r} k="op" u={update}/><C r={r} k="producto" u={update}/><N r={r} k="cantidad" u={update}/><N r={r} k="virgen_kg" u={update}/><C r={r} k="lote_virgen" u={update}/><N r={r} k="reciclado_kg" u={update}/><C r={r} k="lote_reciclado" u={update}/><C r={r} k="pigmento" u={update}/><N r={r} k="pigmento_kg" u={update}/><C r={r} k="lote_pigmento" u={update}/><C r={r} k="molde" u={update}/></tr>)}</tbody></table></div><div className="table-help">Esta es la captura original de lo recibido para la semana. Programación rápida y Gantt usan estas mismas partidas.</div></section>}
function Programacion({rows,machines,update,hoursDay,setHoursDay}:any){return <section className="section"><div className="info-strip">Los tiempos se calculan con <b>ciclo + piezas por ciclo</b>. Si falta el estándar, queda marcado como pendiente y no se inventa un tiempo.<label>Horas productivas/día <input type="number" min="1" max="24" value={hoursDay} onChange={e=>setHoursDay(Number(e.target.value)||1)}/></label></div><div className="table-wrap"><table className="schedule-table"><thead><tr><th>Sec.</th><th>Máquina</th><th>OP</th><th>Producto / Clave</th><th>Pzas</th><th>Molde</th><th>Ciclo s</th><th>Pz/ciclo</th><th>Pz/h</th><th>Horas est.</th><th>Disponibilidad</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><b>{r._seq}</b></td><td><select className="cell" value={r.maquina} onChange={e=>update(r.id,'maquina',e.target.value)}>{machines.map((m:string)=><option key={m}>{m}</option>)}</select></td><td>{r.op||'—'}</td><td><b>{r.producto||'—'}</b></td><td>{r.cantidad?.toLocaleString()||'—'}</td><td>{r.molde||'Pendiente'}</td><td><input className="cell mini" type="number" value={r.ciclo??''} onChange={e=>update(r.id,'ciclo',e.target.value?Number(e.target.value):null)}/></td><td><input className="cell mini" type="number" value={r.pz_ciclo??''} onChange={e=>update(r.id,'pz_ciclo',e.target.value?Number(e.target.value):null)}/></td><td>{r._pzh?Math.round(r._pzh).toLocaleString():'⚠ Catálogo'}</td><td>{r._hrs?`${r._hrs.toFixed(1)} h`:'—'}</td><td>{r._hrs?<span className="status ok">Calculable</span>:<span className="status warn">Pendiente estándar</span>}</td></tr>)}</tbody></table></div></section>}
function Gantt({rows}:any){const grouped=Array.from(new Set(rows.map((r:any)=>r.maquina).filter(Boolean)));return <section className="section"><div className="info-strip">Gantt preliminar de lunes a viernes. Se alimenta de la programación rápida; las partidas sin ciclo/capacidad aparecen pendientes.</div><div className="gantt-v4"><div className="gantt-v4-head"><b>Máquina</b>{['Lunes','Martes','Miércoles','Jueves','Viernes'].map(d=><b key={d}>{d}</b>)}</div>{grouped.map((m:any)=><div className="gantt-v4-row" key={m}><strong>{m}</strong><div className="gantt-track">{rows.filter((r:any)=>r.maquina===m).map((r:any)=><span key={r.id} className={r._hrs?'gantt-job':'gantt-job pending'} title={r._hrs?`${r._hrs.toFixed(1)} h`:'Falta estándar'}>{r.producto||'Sin producto'} {r._hrs&&<small>{r._hrs.toFixed(1)}h</small>}</span>)}</div></div>)}</div></section>}
function C({r,k,u}:any){return <td><input className="cell" value={r[k]||''} onChange={e=>u(r.id,k,e.target.value)}/></td>}
function N({r,k,u}:any){return <td><input className="cell" type="number" step="0.001" value={r[k]??''} onChange={e=>u(r.id,k,e.target.value?Number(e.target.value):null)}/></td>}
