'use client';
import {useMemo,useState} from 'react';
import {seedPrograma,ProgramaRow} from '@/lib/programa';

const machines=['IP-003','IP-004','IP-002','IP-005','IP-006','EP-010','EP-011','EP-008','EP-007','EP-040','IP-001','ARBURG','IP-032','IP-035','IP-039','EP-038','EP-048','IP-040','IP-034','EP-041'];
type Row=ProgramaRow&{semana?:string;fecha_requerida?:string;seleccionado?:boolean};
const empty:Row={maquina:'',producto:'',op:'',cantidad:null,estatus:'PENDIENTE',molde:'',prioridad:'MEDIA',observaciones:'',material_virgen:'',virgen_kg:null,lote_virgen:'',reciclado:'',reciclado_kg:null,lote_reciclado:'',pigmento:'',pigmento_kg:null,lote_pigmento:'',semana:'2026-S39',fecha_requerida:''};

export default function Page(){
 const [rows,setRows]=useState<Row[]>(seedPrograma.map((r,i)=>({...r,id:`seed-${i}`,semana:'2026-S39',prioridad:r.prioridad||'MEDIA'})));
 const [bulk,setBulk]=useState(false); const [txt,setTxt]=useState(''); const [search,setSearch]=useState(''); const [machine,setMachine]=useState('');
 const visible=useMemo(()=>rows.filter(r=>(!machine||r.maquina===machine)&&(!search||`${r.op} ${r.producto}`.toLowerCase().includes(search.toLowerCase()))),[rows,machine,search]);
 const update=(id:string,k:keyof Row,v:any)=>setRows(rs=>rs.map(r=>r.id===id?{...r,[k]:v}:r));
 const addRows=(n:number)=>setRows(rs=>[...rs,...Array.from({length:n},()=>({...empty,id:crypto.randomUUID()}))]);
 const delSelected=()=>setRows(rs=>rs.filter(r=>!r.seleccionado));
 const importar=()=>{const parsed=txt.split(/\r?\n/).filter(Boolean).map(line=>{const p=line.split(/\t|;/);return {...empty,id:crypto.randomUUID(),maquina:(p[0]||'').trim(),op:(p[1]||'').trim(),producto:(p[2]||'').trim(),cantidad:Number((p[3]||'').replace(/,/g,''))||null,virgen_kg:Number(p[4])||null,lote_virgen:(p[5]||'').trim(),reciclado_kg:Number(p[6])||null,lote_reciclado:(p[7]||'').trim(),pigmento:(p[8]||'').trim(),pigmento_kg:Number(p[9])||null,lote_pigmento:(p[10]||'').trim()} as Row});setRows(r=>[...parsed,...r]);setTxt('');setBulk(false)};
 return <>
 <div className="top"><div><div className="title">Planeación semanal</div><div className="muted">Carga rápida de partidas y material liberado · Semana 39 · 21–27 Sep 2026</div></div><div className="actions"><button className="btn secondary" onClick={()=>setBulk(!bulk)}>📋 Pegar Excel</button><button className="btn secondary" onClick={()=>alert('La importación XLSX se conectará en la siguiente etapa.')}>📂 Importar Excel</button></div></div>
 <div className="weekbar"><button>‹</button><div><b>SEMANA 39</b><span>21–27 septiembre 2026</span></div><button>›</button><button className="btn">+ Nueva semana</button></div>
 {bulk&&<div className="card bulk"><b>Carga masiva desde Excel</b><p className="muted small">Orden: Máquina · OP · Producto · Pzas · Virgen kg · Lote virgen · Reciclado kg · Lote reciclado · Pigmento · Pigmento kg · Lote pigmento.</p><textarea className="paste" value={txt} onChange={e=>setTxt(e.target.value)} placeholder={'IP-039\tOP-1234\tS ACT370-4 PRO\t360\t12.5\tV260923\t2.5\tR260923\tNEGRO\t0.20\tPN032'}/><div className="actions"><button className="btn" onClick={importar}>Agregar a la tabla</button><button className="btn secondary" onClick={()=>setBulk(false)}>Cancelar</button></div></div>}
 <section className="section"><div className="quick-toolbar"><div className="filters"><input placeholder="🔎 Buscar OP o producto" value={search} onChange={e=>setSearch(e.target.value)}/><select value={machine} onChange={e=>setMachine(e.target.value)}><option value="">Todas las máquinas</option>{machines.map(m=><option key={m}>{m}</option>)}</select></div><div className="actions"><button className="btn secondary" onClick={()=>addRows(1)}>+ Fila</button><button className="btn secondary" onClick={()=>addRows(10)}>+ 10 filas</button><button className="btn secondary" onClick={delSelected}>Eliminar seleccionadas</button><button className="btn" onClick={()=>alert('Vista lista. El guardado definitivo se conectará a Supabase después de validar el flujo.')}>Guardar programa</button></div></div>
 <div className="table-wrap grouped-wrap"><table className="quick-table"><thead><tr className="group-head"><th></th><th colSpan={4} className="grp order">🏭 ORDEN / PRODUCTO</th><th colSpan={2} className="grp virgin">🧱 MATERIA PRIMA VIRGEN</th><th colSpan={2} className="grp recycle">♻️ RECICLADO</th><th colSpan={3} className="grp pigment">🎨 PIGMENTO</th><th colSpan={3} className="grp plan">📅 PLANEACIÓN</th></tr><tr><th>✓</th><th className="freeze1">Máquina</th><th className="freeze2">OP</th><th className="freeze3">Producto / Clave</th><th>Pzas</th><th>kg</th><th>Lote</th><th>kg</th><th>Lote</th><th>Color / Material</th><th>kg</th><th>Lote</th><th>Molde</th><th>Prioridad</th><th>Fecha requerida</th></tr></thead><tbody>{visible.map(r=><tr key={r.id} className={r.seleccionado?'selected-row':''}><td><input type="checkbox" checked={!!r.seleccionado} onChange={e=>update(r.id!,'seleccionado',e.target.checked)}/></td><td className="freeze1"><select className="cell" value={r.maquina} onChange={e=>update(r.id!,'maquina',e.target.value)}><option value="">—</option>{machines.map(m=><option key={m}>{m}</option>)}</select></td><C r={r} k="op" u={update}/><C r={r} k="producto" u={update} cls="freeze3"/><N r={r} k="cantidad" u={update}/><N r={r} k="virgen_kg" u={update}/><C r={r} k="lote_virgen" u={update}/><N r={r} k="reciclado_kg" u={update}/><C r={r} k="lote_reciclado" u={update}/><C r={r} k="pigmento" u={update}/><N r={r} k="pigmento_kg" u={update}/><C r={r} k="lote_pigmento" u={update}/><C r={r} k="molde" u={update}/><td><select className="cell" value={r.prioridad||'MEDIA'} onChange={e=>update(r.id!,'prioridad',e.target.value)}><option>ALTA</option><option>MEDIA</option><option>BAJA</option></select></td><td><input className="cell" type="date" value={r.fecha_requerida||''} onChange={e=>update(r.id!,'fecha_requerida',e.target.value)}/></td></tr>)}</tbody></table></div>
 <div className="table-help"><span>🟢 Datos identificados</span><span>🟡 Se permite guardar información pendiente</span><span>Las columnas Máquina · OP · Producto permanecen visibles al desplazarte.</span></div></section>
 <section className="section"><div className="section-title-row"><div><h2>Programa semanal guardado</h2><div className="muted small">Vista resumida. Abre una semana desde Historial semanal para consultar producción, personal, materiales, incidencias y reportes.</div></div><span className="count">{rows.length} partidas</span></div><div className="table-wrap"><table className="compact"><thead><tr><th>Máquina</th><th>OP</th><th>Producto</th><th>Pzas</th><th>Material liberado</th><th>Fecha requerida</th><th>Validación</th></tr></thead><tbody>{rows.slice(0,12).map(r=>{const kg=Number(r.virgen_kg||0)+Number(r.reciclado_kg||0)+Number(r.pigmento_kg||0);return <tr key={'sum'+r.id}><td><b>{r.maquina||'—'}</b></td><td>{r.op||'Pendiente'}</td><td>{r.producto||'—'}</td><td>{r.cantidad?.toLocaleString()||'—'}</td><td>{kg?`${kg.toFixed(3)} kg`:'Pendiente'}</td><td>{r.fecha_requerida||'—'}</td><td>{r.maquina&&r.producto?<span className="pill">✓ Identificada</span>:<span className="status warn">⚠ Revisar</span>}</td></tr>})}</tbody></table></div></section>
 </>}
function C({r,k,u,cls=''}:{r:Row,k:keyof Row,u:(id:string,k:keyof Row,v:any)=>void,cls?:string}){return <td className={cls}><input className="cell" value={(r[k] as string)||''} onChange={e=>u(r.id!,k,e.target.value)}/></td>}
function N({r,k,u}:{r:Row,k:keyof Row,u:(id:string,k:keyof Row,v:any)=>void}){return <td><input className="cell" type="number" step="0.001" value={(r[k] as number|null)??''} onChange={e=>u(r.id!,k,e.target.value?Number(e.target.value):null)}/></td>}
