'use client';
import {useMemo,useState} from 'react';
import {seedPrograma,ProgramaRow,estadoClase} from '@/lib/programa';
const machines=['IP-003','IP-004','IP-002','IP-005','IP-006','EP-010','EP-011','EP-008','EP-007','EP-040','IP-001','ARBURG','IP-032','IP-035','IP-039','EP-038','EP-048','IP-040','IP-034','EP-041'];
const empty:ProgramaRow={maquina:'',producto:'',op:'',cantidad:null,estatus:'PENDIENTE',molde:'',fecha:'',turno:'DÍA',prioridad:'MEDIA',observaciones:'',material_virgen:'',virgen_kg:null,lote_virgen:'',reciclado:'',reciclado_kg:null,lote_reciclado:'',pigmento:'',pigmento_kg:null,lote_pigmento:''};
export default function Page(){
 const [rows,setRows]=useState<ProgramaRow[]>(seedPrograma);const [form,setForm]=useState<ProgramaRow>(empty);const [bulk,setBulk]=useState(false);const [txt,setTxt]=useState('');
 const totalKg=useMemo(()=>Number(form.virgen_kg||0)+Number(form.reciclado_kg||0)+Number(form.pigmento_kg||0),[form]);
 const set=(k:keyof ProgramaRow,v:any)=>setForm({...form,[k]:v});
 const add=()=>{if(!form.maquina||!form.producto)return alert('Captura al menos Máquina y Producto.');setRows([{...form,id:crypto.randomUUID()},...rows]);setForm({...empty,maquina:form.maquina,fecha:form.fecha});};
 const change=(i:number,k:keyof ProgramaRow,v:any)=>setRows(rows.map((r,n)=>n===i?{...r,[k]:v}:r));
 const del=(i:number)=>setRows(rows.filter((_,n)=>n!==i));
 const duplicate=(i:number)=>setRows([...rows.slice(0,i+1),{...rows[i],id:crypto.randomUUID()},...rows.slice(i+1)]);
 const importar=()=>{const n=txt.split(/\r?\n/).filter(Boolean).map(l=>{const p=l.split(/\t|;/);return {...empty,maquina:(p[0]||'').trim(),producto:(p[1]||'').trim(),op:(p[2]||'').trim(),cantidad:Number((p[3]||'').replace(/,/g,''))||null,estatus:(p[4]||'PENDIENTE').trim().toUpperCase()} as ProgramaRow});if(n.length)setRows([...n,...rows]);setTxt('');setBulk(false)};
 return <><div className="top"><div><div className="title">Planeación / Carga rápida</div><div className="muted">Captura por campos · material liberado · edición directa del programa</div></div><div className="actions"><button className="btn secondary" onClick={()=>setBulk(!bulk)}>Carga masiva Excel</button><button className="btn secondary" onClick={()=>alert('La plantilla Excel se habilitará al conectar el guardado definitivo.')}>Descargar plantilla</button></div></div>
 {bulk&&<div className="card bulk"><b>Carga masiva</b><p className="muted small">Pega columnas: Máquina · Producto · OP · Cantidad · Estado. Después puedes completar materiales directamente en la tabla.</p><textarea className="paste" value={txt} onChange={e=>setTxt(e.target.value)} placeholder={'IP-039\tACT370-4PRO\tOP-001\t360\tEN PROCESO'}/><div className="actions"><button className="btn" onClick={importar}>Procesar tabla</button><button className="btn secondary" onClick={()=>setBulk(false)}>Cancelar</button></div></div>}
 <div className="capture-grid"><div className="card"><h2>Programa de producción</h2><div className="form form-4"><F label="Máquina"><select value={form.maquina} onChange={e=>set('maquina',e.target.value)}><option value="">Seleccionar</option>{machines.map(x=><option key={x}>{x}</option>)}</select></F><F label="Producto / Clave"><input value={form.producto} onChange={e=>set('producto',e.target.value)}/></F><F label="OP"><input value={form.op} onChange={e=>set('op',e.target.value)}/></F><F label="Cantidad programada"><input type="number" value={form.cantidad??''} onChange={e=>set('cantidad',e.target.value?Number(e.target.value):null)}/></F><F label="Molde / Herramental"><input value={form.molde||''} onChange={e=>set('molde',e.target.value)}/></F><F label="Fecha inicio"><input type="date" value={form.fecha||''} onChange={e=>set('fecha',e.target.value)}/></F><F label="Turno"><select value={form.turno} onChange={e=>set('turno',e.target.value)}><option>DÍA</option><option>NOCHE</option></select></F><F label="Estado"><select value={form.estatus} onChange={e=>set('estatus',e.target.value)}>{['PENDIENTE','SE MONTA HOY','EN PROCESO','SIN MATERIAL','INCIDENCIA / REPARACION','TALLER','MANTENIMIENTO','TERMINADO'].map(x=><option key={x}>{x}</option>)}</select></F><F label="Prioridad"><select value={form.prioridad} onChange={e=>set('prioridad',e.target.value)}><option>ALTA</option><option>MEDIA</option><option>BAJA</option></select></F><F label="Observaciones" wide><input value={form.observaciones||''} onChange={e=>set('observaciones',e.target.value)}/></F></div></div>
 <div className="card"><h2>Material liberado</h2><div className="material-block"><h3>Materia prima virgen</h3><div className="form form-3"><F label="Material"><input value={form.material_virgen||''} onChange={e=>set('material_virgen',e.target.value)}/></F><F label="Cantidad (kg)"><input type="number" step="0.001" value={form.virgen_kg??''} onChange={e=>set('virgen_kg',e.target.value?Number(e.target.value):null)}/></F><F label="Lote"><input value={form.lote_virgen||''} onChange={e=>set('lote_virgen',e.target.value)}/></F></div><h3>Reciclado</h3><div className="form form-3"><F label="Material"><input value={form.reciclado||''} onChange={e=>set('reciclado',e.target.value)}/></F><F label="Cantidad (kg)"><input type="number" step="0.001" value={form.reciclado_kg??''} onChange={e=>set('reciclado_kg',e.target.value?Number(e.target.value):null)}/></F><F label="Lote"><input value={form.lote_reciclado||''} onChange={e=>set('lote_reciclado',e.target.value)}/></F></div><h3>Pigmento</h3><div className="form form-3"><F label="Pigmento / Color"><input value={form.pigmento||''} onChange={e=>set('pigmento',e.target.value)}/></F><F label="Cantidad (kg)"><input type="number" step="0.001" value={form.pigmento_kg??''} onChange={e=>set('pigmento_kg',e.target.value?Number(e.target.value):null)}/></F><F label="Lote"><input value={form.lote_pigmento||''} onChange={e=>set('lote_pigmento',e.target.value)}/></F></div><div className="material-total"><span>Total material liberado</span><b>{totalKg.toFixed(3)} kg</b></div></div></div></div>
 <div className="actions capture-actions"><button className="btn" onClick={add}>Guardar y agregar otro</button><button className="btn secondary" onClick={()=>setForm(empty)}>Limpiar campos</button></div>
 <section className="section"><div className="section-title-row"><div><h2>Programa editable de trabajo</h2><div className="muted small">Edita cualquier celda directamente. Los cambios son visuales en esta versión; todavía no escriben en Supabase.</div></div><span className="count">{rows.length} registros</span></div><div className="table-wrap"><table className="edit-table"><thead><tr>{['Máquina','Producto','OP','Cantidad','Molde','Fecha','Turno','Virgen','Virgen kg','Lote virgen','Reciclado','Rec. kg','Lote rec.','Pigmento','Pig. kg','Lote pig.','Estado','Prioridad','Observaciones','Acciones'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}><TD value={r.maquina} on={v=>change(i,'maquina',v)} list={machines}/><TD value={r.producto} on={v=>change(i,'producto',v)}/><TD value={r.op} on={v=>change(i,'op',v)}/><TD value={r.cantidad??''} on={v=>change(i,'cantidad',v?Number(v):null)} type="number"/><TD value={r.molde||''} on={v=>change(i,'molde',v)}/><TD value={r.fecha||''} on={v=>change(i,'fecha',v)} type="date"/><TD value={r.turno||''} on={v=>change(i,'turno',v)}/><TD value={r.material_virgen||''} on={v=>change(i,'material_virgen',v)}/><TD value={r.virgen_kg??''} on={v=>change(i,'virgen_kg',v?Number(v):null)} type="number"/><TD value={r.lote_virgen||''} on={v=>change(i,'lote_virgen',v)}/><TD value={r.reciclado||''} on={v=>change(i,'reciclado',v)}/><TD value={r.reciclado_kg??''} on={v=>change(i,'reciclado_kg',v?Number(v):null)} type="number"/><TD value={r.lote_reciclado||''} on={v=>change(i,'lote_reciclado',v)}/><TD value={r.pigmento||''} on={v=>change(i,'pigmento',v)}/><TD value={r.pigmento_kg??''} on={v=>change(i,'pigmento_kg',v?Number(v):null)} type="number"/><TD value={r.lote_pigmento||''} on={v=>change(i,'lote_pigmento',v)}/><td><select className={'cell status '+estadoClase(r.estatus)} value={r.estatus} onChange={e=>change(i,'estatus',e.target.value)}>{['PENDIENTE','SE MONTA HOY','EN PROCESO','SIN MATERIAL','INCIDENCIA / REPARACION','TALLER','MANTENIMIENTO','TERMINADO'].map(x=><option key={x}>{x}</option>)}</select></td><TD value={r.prioridad||''} on={v=>change(i,'prioridad',v)}/><TD value={r.observaciones||''} on={v=>change(i,'observaciones',v)}/><td className="row-actions"><button onClick={()=>duplicate(i)}>Duplicar</button><button className="danger-link" onClick={()=>del(i)}>Eliminar</button></td></tr>)}</tbody></table></div></section></>}
function F({label,children,wide=false}:{label:string,children:React.ReactNode,wide?:boolean}){return <div className={'field '+(wide?'wide':'')}><label>{label}</label>{children}</div>}
function TD({value,on,type='text',list}:{value:any,on:(v:string)=>void,type?:string,list?:string[]}){return <td>{list?<select className="cell" value={value} onChange={e=>on(e.target.value)}><option value="">—</option>{list.map(x=><option key={x}>{x}</option>)}</select>:<input className="cell" type={type} step={type==='number'?'0.001':undefined} value={value} onChange={e=>on(e.target.value)}/>}</td>}
