'use client';
import {useEffect,useMemo,useState} from 'react';
import {Allocation,KEYS,Order,Production,Program,read,write,realPiecesFor} from '@/lib/operations';
import {QUALITY_KEYS,QualityRelease,acceptedForAllocation,qread,qwrite,qualityPdfLines} from '@/lib/quality';
import {loadPersonnel} from '@/lib/personnel';
import {loadProcessStandards} from '@/lib/processRuntime';
import {downloadSimplePdf} from '@/lib/simplePdf';

type Candidate={kind:'PRODUCTION'|'PLAN';id:string;allocation:Allocation;order:Order;production?:Production};
const today=()=>new Date().toISOString().slice(0,10);
const norm=(s:string)=>(s||'').trim().toUpperCase().replace(/\s+/g,' ');
const moldCode=(s:string)=>(s||'').split('-MOLDE')[0].split('-ESQUINERO')[0].trim();
const byName=(a:{nombre:string},b:{nombre:string})=>a.nombre.localeCompare(b.nombre,'es',{sensitivity:'base'});
function PersonnelSlots({title,help,max,value,onChange,people}:{title:string;help:string;max:number;value:string[];onChange:(v:string[])=>void;people:{numero:string;nombre:string}[]}){const sorted=[...people].sort(byName);const setSlot=(i:number,next:string)=>{const copy=[...value];if(next)copy[i]=next;else copy.splice(i,1);onChange(copy.filter(Boolean).slice(0,max))};return <label className="personnel-picker">{title}<small>{help} · seleccionados {value.length}/{max}.</small><div className="personnel-slots">{Array.from({length:max},(_,i)=><select key={i} value={value[i]||''} onChange={e=>setSlot(i,e.target.value)}><option value="">{i===0?'Seleccionar…':`Agregar ${i+1}…`}</option>{sorted.map(x=>{const v=`${x.numero} ${x.nombre}`;return <option key={x.numero} value={v} disabled={value.includes(v)&&value[i]!==v}>{x.nombre} · {x.numero}</option>})}</select>)}</div></label>}

export default function CalidadPage(){
 const [programs,setPrograms]=useState<Program[]>([]),[orders,setOrders]=useState<Order[]>([]),[allocs,setAllocs]=useState<Allocation[]>([]),[prod,setProd]=useState<Production[]>([]),[rels,setRels]=useState<QualityRelease[]>([]),[selected,setSelected]=useState('');
 const [result,setResult]=useState<'PASA'|'NO PASA'>('PASA'),[pieces,setPieces]=useState(0),[accepted,setAccepted]=useState(0),[shift,setShift]=useState<'DÍA'|'NOCHE'>('DÍA'),[date,setDate]=useState(today()),[lot,setLot]=useState(''),[cycle,setCycle]=useState<number|null>(null),[operators,setOperators]=useState<string[]>([]),[supervisors,setSupervisors]=useState<string[]>([]),[resp,setResp]=useState('Gustavo Castillo G.'),[obs,setObs]=useState(''),[actualMachine,setActualMachine]=useState(''),[actualMold,setActualMold]=useState(''),[actualCav,setActualCav]=useState<number|null>(null),[editing,setEditing]=useState<QualityRelease|null>(null);
 const load=()=>{setPrograms(read(KEYS.programs,[]));setOrders(read(KEYS.orders,[]));setAllocs(read(KEYS.allocations,[]));setProd(read(KEYS.production,[]));setRels(qread(QUALITY_KEYS.releases,[]))};
 useEffect(()=>{load();addEventListener('anclo-operations-updated',load);return()=>removeEventListener('anclo-operations-updated',load)},[]);
 const people=useMemo(()=>loadPersonnel().filter(x=>x.activo).sort(byName),[]),coordinators=useMemo(()=>people.filter(x=>norm(x.puesto).includes('COORDINADOR')), [people]);
 const standards=useMemo(()=>loadProcessStandards(),[rels,selected]);
 const candidates=useMemo<Candidate[]>(()=>{const releasedProductionIds=new Set(rels.filter(r=>r.estado!=='ANULADA').map(r=>r.productionId));const fromProduction=prod.filter(p=>p.resultado==='PRODUJO'&&!releasedProductionIds.has(p.id)).map(p=>{const a=allocs.find(x=>x.id===p.allocationId),o=orders.find(x=>x.id===p.orderId);return a&&o?{kind:'PRODUCTION' as const,id:`prod:${p.id}`,allocation:a,order:o,production:p}:null}).filter(Boolean) as Candidate[];const productionAllocationIds=new Set(fromProduction.map(x=>x.allocation.id));const activeProgramIds=new Set(programs.filter(p=>p.estado!=='CERRADO').map(p=>p.id));const planned=allocs.filter(a=>a.maquina&&a.cantidad&&a.cantidad>0).map(a=>{const o=orders.find(x=>x.id===a.orderId);if(!o||!activeProgramIds.has(o.programId)||productionAllocationIds.has(a.id))return null;const target=realPiecesFor(a),acc=acceptedForAllocation(a.id,rels);if(acc>=target)return null;return {kind:'PLAN' as const,id:`plan:${a.id}`,allocation:a,order:o};}).filter(Boolean) as Candidate[];return [...fromProduction,...planned]},[prod,allocs,orders,programs,rels]);
 const c=candidates.find(x=>x.id===selected)||candidates[0],a=c?.allocation,o=c?.order,p=c?.production,program=programs.find(x=>x.id===o?.programId);const target=a?realPiecesFor(a):0,alreadyAccepted=a?acceptedForAllocation(a.id,rels):0,remaining=Math.max(0,target-alreadyAccepted);
 const productStandards=useMemo(()=>a?standards.filter(s=>norm(s.producto)===norm(a.producto)):[],[standards,a?.producto]);
 const moldOptions=useMemo(()=>Array.from(new Set(productStandards.map(s=>moldCode(s.herramental)))).sort((x,y)=>x.localeCompare(y,'es',{numeric:true})),[productStandards]);
 const machineOptions=useMemo(()=>Array.from(new Set(productStandards.filter(s=>!actualMold||moldCode(s.herramental)===actualMold).map(s=>s.maquina))).sort((x,y)=>x.localeCompare(y,'es',{numeric:true})),[productStandards,actualMold]);
 useEffect(()=>{if(!c||!a)return;setSelected(c.id);const reported=p?.piezas||0;setPieces(reported);setAccepted(reported);setShift(p?.turno||'DÍA');setDate(p?.fecha||today());setCycle(p?.ciclo??a.ciclo??null);setActualMachine(a.maquina);setActualMold(a.molde);setActualCav(a.cavidades??null);setOperators((p?.operadores||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,3));setSupervisors((p?.supervisores||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,2));setLot('');setResult('PASA');setObs('')},[c?.id]);
 const applyActualStandard=(machine:string,mold:string)=>{const s=productStandards.find(x=>x.maquina===machine&&moldCode(x.herramental)===mold);if(s){setCycle(s.ciclo_s??null);setActualCav(s.cavidades??null)}};
 const setProduced=(n:number)=>{const v=Math.max(0,n||0);setPieces(v);if(result==='PASA')setAccepted(v)};
 const save=()=>{if(!c||!a||!o||pieces<=0)return;let production=p;let nextProd=prod;if(!production){production={id:crypto.randomUUID(),allocationId:a.id,orderId:o.id,fecha:date,turno:shift,operadores:operators.join(', '),supervisores:supervisors.join(', '),kg:null,piezas:pieces,ciclo:cycle,cavidades:actualCav,merma:null,purga:null,horas:null,resultado:'PRODUJO',motivo:'',comentario:lot?`Lote: ${lot}`:''};nextProd=[...prod,production]}else{production={...production,fecha:date,turno:shift,operadores:operators.join(', '),supervisores:supervisors.join(', '),piezas:pieces,ciclo:cycle,cavidades:actualCav,comentario:[production.comentario,lot?`Lote: ${lot}`:''].filter(Boolean).join(' · ')};nextProd=prod.map(x=>x.id===production!.id?production!:x)}write(KEYS.production,nextProd);const acc=result==='PASA'?Math.max(0,Math.min(pieces,accepted)):0;const r:QualityRelease={id:crypto.randomUUID(),productionId:production.id,allocationId:a.id,orderId:o.id,fecha:new Date().toISOString(),fechaProduccion:date,turno:shift,resultado:result,piezasReportadas:pieces,piezasAceptadas:acc,piezasRechazadas:Math.max(0,pieces-acc),operadores:operators,supervisores,responsable:resp,observaciones:obs,pdfFolio:`CAL-${new Date().getFullYear()}-${String(rels.length+1).padStart(5,'0')}`,maquinaPlaneada:a.maquina,moldePlaneado:a.molde,maquinaReal:actualMachine||a.maquina,moldeReal:actualMold||a.molde,cavidadesReales:actualCav,cicloReal:cycle,lote:lot,estado:'ACTIVA',revision:0};qwrite(QUALITY_KEYS.releases,[r,...rels]);if(program?.estado==='LIBERADO')write(KEYS.programs,programs.map(x=>x.id===program.id?{...x,estado:'EN EJECUCIÓN' as const,actualizadoAt:new Date().toISOString()}:x));setSelected('');setPieces(0);setAccepted(0);setObs('');setLot('');load()};
 const saveEdit=()=>{if(!editing)return;const next={...editing,piezasAceptadas:editing.resultado==='PASA'?Math.min(editing.piezasReportadas,Math.max(0,editing.piezasAceptadas)):0,piezasRechazadas:Math.max(0,editing.piezasReportadas-(editing.resultado==='PASA'?editing.piezasAceptadas:0)),revision:(editing.revision||0)+1,actualizadoAt:new Date().toISOString()};qwrite(QUALITY_KEYS.releases,rels.map(r=>r.id===next.id?next:r));setEditing(null);load()};
 const annul=(r:QualityRelease)=>{const reason=window.prompt(`Motivo para anular ${r.pdfFolio}:`);if(!reason)return;qwrite(QUALITY_KEYS.releases,rels.map(x=>x.id===r.id?{...x,estado:'ANULADA' as const,motivoAnulacion:reason,revision:(x.revision||0)+1,actualizadoAt:new Date().toISOString()}:x));load()};
 const relToday=rels.filter(r=>r.fecha.slice(0,10)===today()&&r.estado!=='ANULADA');
 return <><div className="top"><div><div className="title">Calidad · Liberación rápida</div><div className="muted">Planeado y real quedan separados. Si cambió máquina o molde, corrígelo antes de liberar.</div></div></div>
 <div className="grid quality-kpis"><div className="card"><div className="muted">Pendientes de Calidad</div><div className="kpi amber">{candidates.length}</div></div><div className="card"><div className="muted">Liberaciones hoy</div><div className="kpi green">{relToday.filter(x=>x.resultado==='PASA').length}</div></div><div className="card"><div className="muted">Retenidas hoy</div><div className="kpi red">{relToday.filter(x=>x.resultado==='NO PASA').length}</div></div></div>
 <section className="section quality-work"><div><h2>Pendientes</h2><div className="muted quick-note">🏭 = Producción · 📋 = Planeación</div><div className="quality-list">{candidates.map(x=>{const acc=acceptedForAllocation(x.allocation.id,rels),t=realPiecesFor(x.allocation),left=Math.max(0,t-acc);return <button key={x.id} className={x.id===c?.id?'active':''} onClick={()=>setSelected(x.id)}><b>{x.kind==='PRODUCTION'?'🏭':'📋'} {x.allocation.maquina} · {x.allocation.producto}</b><span>{x.order.folioInterno}{x.order.op?` · OP ${x.order.op}`:''}</span><small>{x.production?`${(x.production.piezas||0).toLocaleString()} pzas · ${x.production.turno}`:`Pendientes ${left.toLocaleString()} de ${t.toLocaleString()} pzas`}</small></button>})}</div></div>
 <div className="quality-release"><h2>Captura rápida y liberación</h2>{!c||!a||!o?<p className="muted">Selecciona una partida pendiente.</p>:<><div className="quality-context"><div><small>Origen</small><b>{c.kind==='PRODUCTION'?'🏭 Producción':'📋 Planeación'}</b></div><div><small>Folio / OP</small><b>{o.folioInterno}{o.op?` · ${o.op}`:''}</b></div><div><small>Producto</small><b>{a.producto}</b></div><div><small>Avance / faltante</small><b>{alreadyAccepted.toLocaleString()} / {target.toLocaleString()} · faltan {remaining.toLocaleString()}</b></div></div>
 <div className="actual-change"><div><small>Máquina planeada: <b>{a.maquina}</b></small><label>Máquina real<select value={actualMachine} onChange={e=>{setActualMachine(e.target.value);applyActualStandard(e.target.value,actualMold)}}>{Array.from(new Set([a.maquina,...machineOptions])).sort().map(x=><option key={x}>{x}</option>)}</select></label></div><div><small>Molde planeado: <b>{a.molde}</b></small><label>Molde real<select value={actualMold} onChange={e=>{setActualMold(e.target.value);const ms=Array.from(new Set(productStandards.filter(s=>moldCode(s.herramental)===e.target.value).map(s=>s.maquina))).sort();const m=ms.includes(actualMachine)?actualMachine:(ms[0]||actualMachine);setActualMachine(m);applyActualStandard(m,e.target.value)}}>{Array.from(new Set([a.molde,...moldOptions])).sort().map(x=><option key={x}>{x}</option>)}</select></label></div><div><small>Configuración real</small><b>{actualCav??'—'} cav. · {cycle??'—'} s</b></div></div>
 <div className="quick-release-row"><label>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div><small>Turno *</small><div className="shift-quick"><button className={shift==='DÍA'?'active':''} onClick={()=>setShift('DÍA')}>☀️ DÍA</button><button className={shift==='NOCHE'?'active':''} onClick={()=>setShift('NOCHE')}>🌙 NOCHE</button></div></div></div>
 <div className="quick-release-row"><label className="pieces-main">Piezas producidas *<input autoFocus type="number" min="0" value={pieces||''} onChange={e=>setProduced(Number(e.target.value))}/></label><label>Lote<input value={lot} onChange={e=>setLot(e.target.value)} placeholder="Lote (opcional)"/></label><label>Ciclo real (s)<input type="number" step=".01" value={cycle??''} onChange={e=>setCycle(e.target.value?Number(e.target.value):null)}/></label></div>
 <div className="result-toggle"><button className={result==='PASA'?'pass':''} onClick={()=>{setResult('PASA');setAccepted(pieces)}}>✓ PASA / LIBERAR</button><button className={result==='NO PASA'?'fail':''} onClick={()=>{setResult('NO PASA');setAccepted(0)}}>! NO PASA / RETENER</button></div><label>Piezas aceptadas<input type="number" min="0" max={pieces} value={accepted||''} onChange={e=>setAccepted(Number(e.target.value))}/></label><div className="red"><b>Rechazadas: {Math.max(0,pieces-(result==='PASA'?accepted:0)).toLocaleString()}</b></div>
 <div className="quality-personnel-grid"><PersonnelSlots title="👷 Operadores reales" help="Máximo 3" max={3} value={operators} onChange={setOperators} people={people}/><PersonnelSlots title="👨‍💼 Supervisores reales" help="Máximo 2 · solo Coordinadores" max={2} value={supervisors} onChange={setSupervisors} people={coordinators}/></div><label>Responsable de inspección<input value={resp} onChange={e=>setResp(e.target.value)}/></label><label>Observaciones<textarea value={obs} onChange={e=>setObs(e.target.value)} placeholder="Nota opcional"/></label><button className="primary full-action" onClick={save}>✓ LIBERAR Y SIGUIENTE</button></>}</div></section>
 <section className="section"><div className="section-title-row"><h2>Liberaciones recientes</h2><a className="view-btn" href="/calidad/historial">Ver historial completo</a></div><div className="table-wrap"><table className="quality-history-table"><thead><tr><th>Folio</th><th>Fecha</th><th>Máquina</th><th>OP</th><th>Producto</th><th>Molde</th><th>Turno</th><th>Producidas</th><th>Aceptadas</th><th>Rech.</th><th>Avance OP</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rels.slice(0,10).map(r=>{const ra=allocs.find(x=>x.id===r.allocationId),ro=orders.find(x=>x.id===r.orderId),av=acceptedForAllocation(r.allocationId,rels),tt=ra?realPiecesFor(ra):0;return <tr key={r.id} className={r.estado==='ANULADA'?'row-annulled':''}><td>{r.pdfFolio}{(r.revision||0)>0?<small> Rev.{r.revision}</small>:''}</td><td>{new Date(r.fecha).toLocaleString('es-MX')}</td><td>{r.maquinaReal||r.maquinaPlaneada||ra?.maquina||'—'}</td><td>{ro?.op||ro?.folioInterno||'—'}</td><td>{ra?.producto||'—'}</td><td>{r.moldeReal||r.moldePlaneado||ra?.molde||'—'}</td><td>{r.turno||'—'}</td><td>{r.piezasReportadas.toLocaleString()}</td><td>{r.piezasAceptadas.toLocaleString()}</td><td>{r.piezasRechazadas.toLocaleString()}</td><td>{av.toLocaleString()} / {tt.toLocaleString()}</td><td><b>{r.estado==='ANULADA'?'ANULADA':r.resultado}</b></td><td><div className="row-actions"><button className="view-btn" onClick={()=>setEditing({...r,maquinaReal:r.maquinaReal||ra?.maquina,moldeReal:r.moldeReal||ra?.molde,fechaProduccion:r.fechaProduccion||r.fecha.slice(0,10),turno:r.turno||'DÍA'})}>✏ Editar</button><button className="view-btn" onClick={()=>downloadSimplePdf(`${r.pdfFolio}.pdf`,'ANCLO PLASTICOS - LIBERACION DE CALIDAD',qualityPdfLines(r,{producto:ra?.producto,op:ro?.op||ro?.folioInterno}))}>PDF</button>{r.estado!=='ANULADA'&&<button className="danger-link" onClick={()=>annul(r)}>Anular</button>}</div></td></tr>})}</tbody></table></div></section>
 {editing&&<div className="edit-release"><div className="edit-release-card"><div className="section-title-row"><h2>Editar {editing.pdfFolio}</h2><button className="secondary" onClick={()=>setEditing(null)}>Cerrar</button></div><p className="muted">La corrección conserva el folio y aumenta la revisión. El avance se recalcula con el valor corregido.</p><div className="quality-form-grid"><label>Fecha producción<input type="date" value={editing.fechaProduccion||''} onChange={e=>setEditing({...editing,fechaProduccion:e.target.value})}/></label><label>Turno<select value={editing.turno||'DÍA'} onChange={e=>setEditing({...editing,turno:e.target.value as 'DÍA'|'NOCHE'})}><option>DÍA</option><option>NOCHE</option></select></label><label>Máquina real<select value={editing.maquinaReal||''} onChange={e=>setEditing({...editing,maquinaReal:e.target.value})}>{Array.from(new Set(standards.map(s=>s.maquina))).sort().map(x=><option key={x}>{x}</option>)}</select></label><label>Molde real<input value={editing.moldeReal||''} onChange={e=>setEditing({...editing,moldeReal:e.target.value})}/></label><label>Producidas<input type="number" value={editing.piezasReportadas} onChange={e=>setEditing({...editing,piezasReportadas:Number(e.target.value)})}/></label><label>Aceptadas<input type="number" value={editing.piezasAceptadas} onChange={e=>setEditing({...editing,piezasAceptadas:Number(e.target.value)})}/></label><label>Lote<input value={editing.lote||''} onChange={e=>setEditing({...editing,lote:e.target.value})}/></label><label>Ciclo real<input type="number" step=".01" value={editing.cicloReal??''} onChange={e=>setEditing({...editing,cicloReal:e.target.value?Number(e.target.value):null})}/></label><label>Responsable<input value={editing.responsable} onChange={e=>setEditing({...editing,responsable:e.target.value})}/></label><label className="span-2">Observaciones<input value={editing.observaciones} onChange={e=>setEditing({...editing,observaciones:e.target.value})}/></label></div><button className="primary full-action" onClick={saveEdit}>✓ GUARDAR CORRECCIÓN</button></div></div>}
 </>;
}
