'use client';
import {useEffect,useMemo,useState} from 'react';
import {Allocation,KEYS,Order,Production,Program,read} from '@/lib/operations';
import {QUALITY_KEYS,QualityRelease,qread,qwrite} from '@/lib/quality';
import {initialPersonnel} from '@/lib/personnel';
import {downloadSimplePdf} from '@/lib/simplePdf';

export default function CalidadPage(){
 const [programs,setPrograms]=useState<Program[]>([]),[orders,setOrders]=useState<Order[]>([]),[allocs,setAllocs]=useState<Allocation[]>([]),[prod,setProd]=useState<Production[]>([]),[rels,setRels]=useState<QualityRelease[]>([]),[selected,setSelected]=useState(''),[result,setResult]=useState<'PASA'|'NO PASA'>('PASA'),[accepted,setAccepted]=useState(0),[operators,setOperators]=useState<string[]>([]),[resp,setResp]=useState('Gustavo Castillo G.'),[obs,setObs]=useState('');
 const load=()=>{setPrograms(read(KEYS.programs,[]));setOrders(read(KEYS.orders,[]));setAllocs(read(KEYS.allocations,[]));setProd(read(KEYS.production,[]));setRels(qread(QUALITY_KEYS.releases,[]))};useEffect(()=>{load();addEventListener('anclo-operations-updated',load);return()=>removeEventListener('anclo-operations-updated',load)},[]);
 const releasedIds=new Set(rels.map(r=>r.productionId)); const pending=prod.filter(p=>p.resultado==='PRODUJO'&&!releasedIds.has(p.id)); const p=pending.find(x=>x.id===selected)||pending[0];
 const a=allocs.find(x=>x.id===p?.allocationId),o=orders.find(x=>x.id===p?.orderId),program=programs.find(x=>x.id===o?.programId);
 useEffect(()=>{if(p){setSelected(p.id);setAccepted(p.piezas||0);setOperators((p.operadores||'').split(',').map(x=>x.trim()).filter(Boolean))}},[p?.id]);
 const save=()=>{if(!p||!a||!o)return;const rep=p.piezas||0,acc=result==='PASA'?Math.max(0,Math.min(rep,accepted)):0;const r:QualityRelease={id:crypto.randomUUID(),productionId:p.id,allocationId:a.id,orderId:o.id,fecha:new Date().toISOString(),resultado:result,piezasReportadas:rep,piezasAceptadas:acc,piezasRechazadas:Math.max(0,rep-acc),operadores, responsable:resp,observaciones:obs,pdfFolio:`CAL-${new Date().getFullYear()}-${String(rels.length+1).padStart(5,'0')}`};qwrite(QUALITY_KEYS.releases,[r,...rels]);setObs('');load()};
 const today=rels.filter(r=>r.fecha.slice(0,10)===new Date().toISOString().slice(0,10));
 return <><div className="top"><div><div className="title">Calidad · Liberación de producción</div><div className="muted">La producción validada actualiza el avance oficial de la OP.</div></div></div>
 <div className="grid quality-kpis"><div className="card"><div className="muted">Pendientes de validar</div><div className="kpi amber">{pending.length}</div></div><div className="card"><div className="muted">Liberaciones hoy</div><div className="kpi green">{today.filter(x=>x.resultado==='PASA').length}</div></div><div className="card"><div className="muted">Retenidas hoy</div><div className="kpi red">{today.filter(x=>x.resultado==='NO PASA').length}</div></div></div>
 <section className="section quality-work"><div><h2>Producción pendiente</h2>{pending.length===0?<div className="empty-state"><b>✓</b><span>No hay producción pendiente de Calidad.</span></div>:<div className="quality-list">{pending.map(x=>{const aa=allocs.find(y=>y.id===x.allocationId),oo=orders.find(y=>y.id===x.orderId);return <button key={x.id} className={x.id===p?.id?'active':''} onClick={()=>setSelected(x.id)}><b>{aa?.maquina} · {aa?.producto}</b><span>{oo?.folioInterno}{oo?.op?` · OP ${oo.op}`:''}</span><small>{(x.piezas||0).toLocaleString()} pzas · {x.turno} · {x.fecha}</small></button>})}</div>}</div>
 <div className="quality-release"><h2>Validar y liberar</h2>{!p||!a||!o?<p className="muted">Selecciona una producción pendiente.</p>:<><div className="quality-context"><div><small>Programa</small><b>{program?.nombre||'—'}</b></div><div><small>Folio / OP</small><b>{o.folioInterno}{o.op?` · ${o.op}`:''}</b></div><div><small>Producto</small><b>{a.producto}</b></div><div><small>Máquina</small><b>{a.maquina}</b></div><div><small>Molde</small><b>{a.molde} · {a.moldeDescripcion||'—'} · {a.cavidades??'—'} cav.</b></div><div><small>Producción reportada</small><b>{(p.piezas||0).toLocaleString()} pzas</b></div></div>
 <div className="result-toggle"><button className={result==='PASA'?'pass':''} onClick={()=>setResult('PASA')}>✓ PASA / LIBERAR</button><button className={result==='NO PASA'?'fail':''} onClick={()=>setResult('NO PASA')}>! NO PASA / RETENER</button></div>
 <label>Piezas aceptadas<input type="number" value={accepted} disabled={result==='NO PASA'} onChange={e=>setAccepted(Number(e.target.value))}/></label>
 <label>Operadores reales <small>Si Planeación/Producción no los cargó, selecciónalos aquí.</small><select multiple value={operators} onChange={e=>setOperators(Array.from(e.currentTarget.selectedOptions).map(x=>x.value))}>{initialPersonnel().map(x=><option key={x.numero} value={`${x.numero} ${x.nombre}`}>{x.numero} · {x.nombre}</option>)}</select></label>
 <label>Responsable de inspección<input value={resp} onChange={e=>setResp(e.target.value)}/></label><label>Observaciones<textarea value={obs} onChange={e=>setObs(e.target.value)} placeholder={result==='NO PASA'?'Describe defecto, condición o acción requerida.':'Nota opcional'}/></label>
 <button className="btn" onClick={save} disabled={!resp.trim()||(result==='NO PASA'&&!obs.trim())}>Guardar liberación</button></>}</div></section>
 <section className="section"><div className="section-title-row"><h2>Liberaciones recientes</h2><a className="btn secondary" href="/calidad/historial">Ver historial completo</a></div><div className="table-wrap"><table><thead><tr><th>Folio</th><th>Fecha</th><th>Resultado</th><th>Aceptadas</th><th>Rechazadas</th><th>PDF</th></tr></thead><tbody>{rels.slice(0,10).map(r=><tr key={r.id}><td>{r.pdfFolio}</td><td>{new Date(r.fecha).toLocaleString('es-MX')}</td><td><span className={'result-pill '+(r.resultado==='PASA'?'cumplida':'no-cumplida')}>{r.resultado}</span></td><td>{r.piezasAceptadas.toLocaleString()}</td><td>{r.piezasRechazadas.toLocaleString()}</td><td><button className="view-btn" onClick={()=>downloadSimplePdf(`${r.pdfFolio}.pdf`,'ANCLO PLASTICOS - LIBERACION DE CALIDAD',[`Folio: ${r.pdfFolio}`,`Fecha: ${new Date(r.fecha).toLocaleString('es-MX')}`,`Resultado: ${r.resultado}`,`Piezas reportadas: ${r.piezasReportadas}`,`Piezas aceptadas: ${r.piezasAceptadas}`,`Piezas rechazadas: ${r.piezasRechazadas}`,`Operadores: ${r.operadores.join(', ')||'--'}`,`Responsable: ${r.responsable}`,`Observaciones: ${r.observaciones||'--'}`])}>Descargar PDF</button></td></tr>)}</tbody></table></div></section></>}
