'use client';
import {useEffect,useMemo,useState} from 'react';
import {Allocation,KEYS,Order,Production,Program,read,write} from '@/lib/operations';
import {QUALITY_KEYS,QualityRelease,acceptedForAllocation,qread,qwrite} from '@/lib/quality';
import {loadPersonnel} from '@/lib/personnel';
import {downloadSimplePdf} from '@/lib/simplePdf';

type Candidate={kind:'PRODUCTION'|'PLAN';id:string;allocation:Allocation;order:Order;production?:Production};
const today=()=>new Date().toISOString().slice(0,10);

const byName=(a:{nombre:string},b:{nombre:string})=>a.nombre.localeCompare(b.nombre,'es',{sensitivity:'base'});

function PersonnelSlots({title,help,max,value,onChange,people}:{title:string;help:string;max:number;value:string[];onChange:(v:string[])=>void;people:{numero:string;nombre:string}[]}){
 const sorted=[...people].sort(byName);
 const setSlot=(index:number,next:string)=>{const copy=[...value];if(next){copy[index]=next}else{copy.splice(index,1)};onChange(copy.filter(Boolean).slice(0,max))};
 return <label className="personnel-picker">{title}<small>{help} · seleccionados {value.length}/{max}.</small><div className="personnel-slots">{Array.from({length:max},(_,i)=><select key={i} value={value[i]||''} onChange={e=>setSlot(i,e.target.value)}><option value="">{i===0?'Seleccionar…':`Agregar ${i+1}…`}</option>{sorted.map(x=>{const v=`${x.numero} ${x.nombre}`;return <option key={x.numero} value={v} disabled={value.includes(v)&&value[i]!==v}>{x.nombre} · {x.numero}</option>})}</select>)}</div></label>
}

export default function CalidadPage(){
 const [programs,setPrograms]=useState<Program[]>([]),[orders,setOrders]=useState<Order[]>([]),[allocs,setAllocs]=useState<Allocation[]>([]),[prod,setProd]=useState<Production[]>([]),[rels,setRels]=useState<QualityRelease[]>([]),[selected,setSelected]=useState('');
 const [result,setResult]=useState<'PASA'|'NO PASA'>('PASA'),[pieces,setPieces]=useState(0),[accepted,setAccepted]=useState(0),[shift,setShift]=useState<'DÍA'|'NOCHE'>('DÍA'),[date,setDate]=useState(today()),[lot,setLot]=useState(''),[cycle,setCycle]=useState<number|null>(null),[operators,setOperators]=useState<string[]>([]),[supervisors,setSupervisors]=useState<string[]>([]),[resp,setResp]=useState('Gustavo Castillo G.'),[obs,setObs]=useState('');
 const load=()=>{setPrograms(read(KEYS.programs,[]));setOrders(read(KEYS.orders,[]));setAllocs(read(KEYS.allocations,[]));setProd(read(KEYS.production,[]));setRels(qread(QUALITY_KEYS.releases,[]))};
 useEffect(()=>{load();addEventListener('anclo-operations-updated',load);return()=>removeEventListener('anclo-operations-updated',load)},[]);
 const candidates=useMemo<Candidate[]>(()=>{
  const releasedProductionIds=new Set(rels.map(r=>r.productionId));
  const fromProduction=prod.filter(p=>p.resultado==='PRODUJO'&&!releasedProductionIds.has(p.id)).map(p=>{const a=allocs.find(x=>x.id===p.allocationId),o=orders.find(x=>x.id===p.orderId);return a&&o?{kind:'PRODUCTION' as const,id:`prod:${p.id}`,allocation:a,order:o,production:p}:null}).filter(Boolean) as Candidate[];
  const productionAllocationIds=new Set(fromProduction.map(x=>x.allocation.id));
  const activeProgramIds=new Set(programs.filter(p=>p.estado!=='CERRADO').map(p=>p.id));
  const planned=allocs.filter(a=>a.maquina&&a.cantidad&&a.cantidad>0).map(a=>{const o=orders.find(x=>x.id===a.orderId);if(!o||!activeProgramIds.has(o.programId)||productionAllocationIds.has(a.id))return null;const acceptedQty=acceptedForAllocation(a.id,rels);if(acceptedQty>=(a.cantidad||0))return null;return {kind:'PLAN' as const,id:`plan:${a.id}`,allocation:a,order:o};}).filter(Boolean) as Candidate[];
  return [...fromProduction,...planned];
 },[prod,allocs,orders,programs,rels]);
 const c=candidates.find(x=>x.id===selected)||candidates[0]; const a=c?.allocation,o=c?.order,p=c?.production,program=programs.find(x=>x.id===o?.programId);
 const alreadyAccepted=a?acceptedForAllocation(a.id,rels):0,remaining=Math.max(0,(a?.cantidad||0)-alreadyAccepted);
 useEffect(()=>{if(!c)return;setSelected(c.id);const reported=p?.piezas||0;setPieces(reported);setAccepted(reported);setShift(p?.turno||'DÍA');setDate(p?.fecha||today());setCycle(p?.ciclo??a?.ciclo??null);setOperators((p?.operadores||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,3));setSupervisors((p?.supervisores||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,2));setLot('');setResult('PASA');setObs('')},[c?.id]);
 const setProduced=(n:number)=>{const v=Math.max(0,n||0);setPieces(v);if(result==='PASA')setAccepted(v)};
 const save=()=>{if(!c||!a||!o||pieces<=0)return;let production=p;let nextProd=prod;
  if(!production){production={id:crypto.randomUUID(),allocationId:a.id,orderId:o.id,fecha:date,turno:shift,operadores:operators.join(', '),supervisores:supervisors.join(', '),kg:null,piezas:pieces,ciclo:cycle,cavidades:a.cavidades,merma:null,purga:null,horas:null,resultado:'PRODUJO',motivo:'',comentario:lot?`Lote: ${lot}`:''};nextProd=[...prod,production];write(KEYS.production,nextProd)}
  else {production={...production,fecha:date,turno:shift,operadores:operators.join(', '),supervisores:supervisors.join(', '),piezas:pieces,ciclo:cycle,comentario:[production.comentario,lot?`Lote: ${lot}`:''].filter(Boolean).join(' · ')};nextProd=prod.map(x=>x.id===production!.id?production!:x);write(KEYS.production,nextProd)}
  const acc=result==='PASA'?Math.max(0,Math.min(pieces,accepted)):0;const r:QualityRelease={id:crypto.randomUUID(),productionId:production.id,allocationId:a.id,orderId:o.id,fecha:new Date().toISOString(),resultado:result,piezasReportadas:pieces,piezasAceptadas:acc,piezasRechazadas:Math.max(0,pieces-acc),operadores:operators,supervisores:supervisors,responsable:resp,observaciones:[lot?`Lote: ${lot}`:'',obs].filter(Boolean).join(' · '),pdfFolio:`CAL-${new Date().getFullYear()}-${String(rels.length+1).padStart(5,'0')}`};qwrite(QUALITY_KEYS.releases,[r,...rels]);
  if(program?.estado==='LIBERADO'){write(KEYS.programs,programs.map(x=>x.id===program.id?{...x,estado:'EN EJECUCIÓN' as const,actualizadoAt:new Date().toISOString()}:x))}
  setSelected('');setPieces(0);setAccepted(0);setObs('');setLot('');load();
 };
 const relToday=rels.filter(r=>r.fecha.slice(0,10)===today());
 return <><div className="top"><div><div className="title">Calidad · Liberación rápida</div><div className="muted">Puedes tomar una producción reportada o capturar directamente desde una partida planeada.</div></div></div>
 <div className="grid quality-kpis"><div className="card"><div className="muted">Pendientes de Calidad</div><div className="kpi amber">{candidates.length}</div></div><div className="card"><div className="muted">Liberaciones hoy</div><div className="kpi green">{relToday.filter(x=>x.resultado==='PASA').length}</div></div><div className="card"><div className="muted">Retenidas hoy</div><div className="kpi red">{relToday.filter(x=>x.resultado==='NO PASA').length}</div></div></div>
 <section className="section quality-work"><div><h2>Pendientes</h2><div className="muted quick-note">🏭 = ya reportada en Producción · 📋 = tomada directamente de Planeación</div>{candidates.length===0?<div className="empty-state"><b>✓</b><span>No hay partidas pendientes de Calidad.</span></div>:<div className="quality-list">{candidates.map(x=>{const acceptedQty=acceptedForAllocation(x.allocation.id,rels),left=Math.max(0,(x.allocation.cantidad||0)-acceptedQty);return <button key={x.id} className={x.id===c?.id?'active':''} onClick={()=>setSelected(x.id)}><b>{x.kind==='PRODUCTION'?'🏭':'📋'} {x.allocation.maquina} · {x.allocation.producto}</b><span>{x.order.folioInterno}{x.order.op?` · OP ${x.order.op}`:''}</span><small>{x.production?`${(x.production.piezas||0).toLocaleString()} pzas · ${x.production.turno} · ${x.production.fecha}`:`Pendientes ${left.toLocaleString()} de ${(x.allocation.cantidad||0).toLocaleString()} pzas`}</small></button>})}</div>}</div>
 <div className="quality-release"><h2>Captura rápida y liberación</h2>{!c||!a||!o?<p className="muted">Selecciona una partida pendiente.</p>:<><div className="quality-context"><div><small>Origen</small><b>{c.kind==='PRODUCTION'?'🏭 Producción reportada':'📋 Planeación'}</b></div><div><small>Folio / OP</small><b>{o.folioInterno}{o.op?` · ${o.op}`:''}</b></div><div><small>Producto</small><b>{a.producto}</b></div><div><small>Máquina</small><b>{a.maquina}</b></div><div><small>Molde</small><b>{a.molde} · {a.cavidades??'—'} cav.</b></div><div><small>Avance / faltante</small><b>{alreadyAccepted.toLocaleString()} / {(a.cantidad||0).toLocaleString()} · faltan {remaining.toLocaleString()}</b></div></div>
 <div className="quick-release-row"><label>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div><small>Turno *</small><div className="shift-quick"><button className={shift==='DÍA'?'active':''} onClick={()=>setShift('DÍA')}>☀️ DÍA</button><button className={shift==='NOCHE'?'active':''} onClick={()=>setShift('NOCHE')}>🌙 NOCHE</button></div></div></div>
 <div className="quick-release-row"><label className="pieces-main">Piezas producidas *<input autoFocus type="number" min="0" value={pieces||''} onChange={e=>setProduced(Number(e.target.value))} placeholder="0"/></label><label>Lote<input value={lot} onChange={e=>setLot(e.target.value)} placeholder="Lote (opcional)"/></label><label>Ciclo real (s)<input type="number" step=".01" value={cycle??''} onChange={e=>setCycle(e.target.value?Number(e.target.value):null)}/></label></div>
 <div className="result-toggle"><button className={result==='PASA'?'pass':''} onClick={()=>{setResult('PASA');setAccepted(pieces)}}>✓ PASA / LIBERAR</button><button className={result==='NO PASA'?'fail':''} onClick={()=>{setResult('NO PASA');setAccepted(0)}}>! NO PASA / RETENER</button></div>
 {result==='PASA'&&<label>Piezas aceptadas <small>Por defecto son iguales a las producidas; cambia solo si hubo rechazo.</small><input type="number" min="0" max={pieces} value={accepted||''} onChange={e=>setAccepted(Number(e.target.value))}/><span className="reject-preview">Rechazadas: {Math.max(0,pieces-accepted).toLocaleString()}</span></label>}
 <div className="quality-personnel-grid"><PersonnelSlots title="👷 Operadores reales" help="Máximo 3. Si ya estaban reportados aparecen precargados" max={3} value={operators} onChange={setOperators} people={loadPersonnel().filter(x=>x.activo)}/><PersonnelSlots title="👨‍💼 Supervisores reales" help="Máximo 2. Solo Coordinadores; se guardan por fecha, turno y máquina" max={2} value={supervisors} onChange={setSupervisors} people={loadPersonnel().filter(x=>x.activo&&x.puesto.trim().toLocaleLowerCase('es-MX')==='coordinador')}/></div>
 <label>Responsable de inspección<input value={resp} onChange={e=>setResp(e.target.value)}/></label><label>Observaciones<textarea value={obs} onChange={e=>setObs(e.target.value)} placeholder={result==='NO PASA'?'Describe defecto, condición o acción requerida.':'Nota opcional'}/></label>
 <button className="btn release-next" onClick={save} disabled={!resp.trim()||pieces<=0||(result==='NO PASA'&&!obs.trim())}>✓ LIBERAR Y SIGUIENTE</button></>}</div></section>
 <section className="section"><div className="section-title-row"><h2>Liberaciones recientes</h2><a className="btn secondary" href="/calidad/historial">Ver historial completo</a></div><div className="table-wrap"><table><thead><tr><th>Folio</th><th>Fecha</th><th>Resultado</th><th>Aceptadas</th><th>Rechazadas</th><th>PDF</th></tr></thead><tbody>{rels.slice(0,10).map(r=><tr key={r.id}><td>{r.pdfFolio}</td><td>{new Date(r.fecha).toLocaleString('es-MX')}</td><td><span className={'result-pill '+(r.resultado==='PASA'?'cumplida':'no-cumplida')}>{r.resultado}</span></td><td>{r.piezasAceptadas.toLocaleString()}</td><td>{r.piezasRechazadas.toLocaleString()}</td><td><button className="view-btn" onClick={()=>downloadSimplePdf(`${r.pdfFolio}.pdf`,'ANCLO PLASTICOS - LIBERACION DE CALIDAD',[`Folio: ${r.pdfFolio}`,`Fecha: ${new Date(r.fecha).toLocaleString('es-MX')}`,`Resultado: ${r.resultado}`,`Piezas reportadas: ${r.piezasReportadas}`,`Piezas aceptadas: ${r.piezasAceptadas}`,`Piezas rechazadas: ${r.piezasRechazadas}`,`Operadores: ${r.operadores.join(', ')||'--'}`,`Supervisores: ${(r.supervisores||[]).join(', ')||'--'}`,`Responsable: ${r.responsable}`,`Observaciones: ${r.observaciones||'--'}`])}>Descargar PDF</button></td></tr>)}</tbody></table></div></section></>}
