'use client';
import {useState} from 'react';
const parts=[
 {m:'IP-039',op:'OP-12345',p:'S ACT370-4 PRO',plan:360,real:350,kg:15.2,people:3,inc:1},
 {m:'IP-039',op:'OP-12346',p:'S ACN370-4 PRO',plan:460,real:460,kg:18.25,people:2,inc:0},
 {m:'EP-048',op:'OP-12347',p:'AG14',plan:500000,real:485200,kg:250,people:3,inc:2}
];
export default function Page(){const [open,setOpen]=useState(0);return <><div className="top"><div><div className="title">Historial semanal</div><div className="muted">Expediente completo de producción por semana</div></div><div className="actions"><button className="btn secondary">Descargar Excel</button><button className="btn secondary">Descargar PDF</button></div></div><div className="weekbar"><button>‹</button><div><b>SEMANA 39</b><span>21–27 septiembre 2026 · En ejecución</span></div><button>›</button></div><div className="grid"><K t="Partidas" v="28"/><K t="Máquinas utilizadas" v="14"/><K t="Producción" v="1,470,000"/><K t="Horas de paro" v="18.4 h"/></div><div className="tabs"><button className="active">Partidas</button><button>Producción</button><button>Personal</button><button>Materiales</button><button>Incidencias</button><button>Gantt</button><button>Reportes</button></div><section className="section"><div className="table-wrap"><table className="compact history-table"><thead><tr><th></th><th>Máquina</th><th>OP</th><th>Producto</th><th>Programado</th><th>Producido</th><th>Cumpl.</th><th>Material</th><th>Personal</th><th>Incidencias</th></tr></thead><tbody>{parts.map((x,i)=><FragmentRow key={x.op} x={x} i={i} open={open} setOpen={setOpen}/>)}</tbody></table></div></section></>}
function FragmentRow({x,i,open,setOpen}:{x:any,i:number,open:number,setOpen:(n:number)=>void}){const pct=(x.real/x.plan*100).toFixed(1);return <><tr className="history-main" onClick={()=>setOpen(open===i?-1:i)}><td>{open===i?'▼':'▶'}</td><td><b>{x.m}</b></td><td><b>{x.op}</b></td><td><b>{x.p}</b></td><td>{x.plan.toLocaleString()}</td><td>{x.real.toLocaleString()}</td><td>{pct}%</td><td>{x.kg} kg</td><td>{x.people}</td><td>{x.inc}</td></tr>{open===i&&<tr><td colSpan={10} className="detail-cell"><div className="detail-grid"><Box title="PRODUCCIÓN"><table><thead><tr><th>Fecha</th><th>Turno</th><th>Operadores</th><th>Horas</th><th>Pzas</th><th>Merma</th><th>Purga</th></tr></thead><tbody><tr><td>22/09</td><td>Día</td><td>105 Juan / 112 Pedro</td><td>8.0</td><td>170</td><td>0.30 kg</td><td>0.10 kg</td></tr><tr><td>22/09</td><td>Noche</td><td>118 Carlos</td><td>8.0</td><td>180</td><td>0.20 kg</td><td>0.05 kg</td></tr></tbody></table></Box><Box title="MATERIALES Y TRAZABILIDAD"><table><thead><tr><th>Tipo</th><th>Material</th><th>Liberado</th><th>Consumido</th><th>Lote</th></tr></thead><tbody><tr><td>Virgen</td><td>Nylon</td><td>12.50 kg</td><td>12.10 kg</td><td>V260923</td></tr><tr><td>Reciclado</td><td>Molido</td><td>2.50 kg</td><td>2.30 kg</td><td>R260923</td></tr><tr><td>Pigmento</td><td>Negro</td><td>0.20 kg</td><td>0.18 kg</td><td>PN032</td></tr></tbody></table></Box><Box title="MOLDE / PROCESO"><table><thead><tr><th>Molde</th><th>Máquina</th><th>Cav. estándar</th><th>Cav. reales</th><th>Ciclo estándar</th><th>Ciclo real</th></tr></thead><tbody><tr><td>M-XXX</td><td>{x.m}</td><td>10</td><td>10</td><td>14.0 s</td><td>14.35 s</td></tr></tbody></table></Box><Box title="INCIDENCIAS"><table><thead><tr><th>Fecha</th><th>Inicio</th><th>Fin</th><th>Duración</th><th>Causa</th><th>Observaciones</th></tr></thead><tbody><tr><td>22/09</td><td>13:20</td><td>14:05</td><td>45 min</td><td>Ajuste de máquina</td><td>Ajuste de parámetros</td></tr></tbody></table></Box></div><div className="actions"><button className="btn secondary">Descargar reporte OP</button><button className="btn secondary">Editar registro</button></div><div className="muted small demo-note">Datos mostrados como ejemplo visual hasta conectar los registros reales de Supabase.</div></td></tr>}</>}
function Box({title,children}:{title:string,children:React.ReactNode}){return <div className="detail-box"><h3>{title}</h3>{children}</div>}
function K({t,v}:{t:string,v:string}){return <div className="card"><div className="muted">{t}</div><div className="kpi">{v}</div></div>}
