'use client';
import {seedPrograma,estadoClase} from '@/lib/programa';
const maquinas=['IP-003','IP-004','IP-002','IP-005','IP-006','EP-010','EP-011','EP-008','EP-007','EP-040','IP-001','ARBURG','IP-032','IP-035','IP-039','EP-038','EP-048','IP-040','IP-034','EP-041'];
export default function OperationsDashboard(){
 const current=maquinas.map(m=>({m,r:seedPrograma.find(x=>x.maquina===m&&x.estatus==='EN PROCESO')||seedPrograma.find(x=>x.maquina===m&&x.estatus.includes('INCIDENCIA'))||seedPrograma.find(x=>x.maquina===m&&x.estatus==='SIN MATERIAL')||seedPrograma.find(x=>x.maquina===m&&x.estatus==='SE MONTA HOY')}));
 const prod=current.filter(x=>x.r?.estatus==='EN PROCESO').length, par=current.filter(x=>x.r&&(x.r.estatus.includes('INCIDENCIA')||x.r.estatus==='SIN MATERIAL')).length, prep=current.filter(x=>x.r?.estatus==='SE MONTA HOY').length;
 return <><div className="top"><div><div className="title">Monitoreo de planta</div><div className="muted">Estado operativo · programa actual y cola de trabajo</div></div><span className="live">● OPERACIÓN</span></div>
 <div className="grid"><div className="card"><div className="muted">Produciendo</div><div className="kpi green">{prod}</div></div><div className="card"><div className="muted">Paradas / sin material</div><div className="kpi red">{par}</div></div><div className="card"><div className="muted">Preparación / montaje</div><div className="kpi amber">{prep}</div></div><div className="card"><div className="muted">Sin programa visible</div><div className="kpi">{20-prod-par-prep}</div></div></div>
 <section className="section"><h2>Plano operativo</h2><div className="machine-grid">{current.map(({m,r})=><div className={'machine '+estadoClase(r?.estatus||'')} key={m}><div className="machine-head"><b>{m}</b><span>{r?.estatus||'SIN PROGRAMA'}</span></div><div className="machine-product">{r?.producto||'—'}</div><small>{r?.orden?`OP / Cantidad: ${r.orden}`:'Sin OP registrada'}</small>{seedPrograma.filter(x=>x.maquina===m&&x.estatus==='PENDIENTE').length>0&&<div className="queue">+ {seedPrograma.filter(x=>x.maquina===m&&x.estatus==='PENDIENTE').length} pendiente(s)</div>}</div>)}</div></section></>}
