'use client';
import {useEffect,useState} from 'react';
import {machineMaster} from '@/lib/machines';
import {Allocation,KEYS,Order,Production,Program,read,scheduleAllocations} from '@/lib/operations';
const defaultLayout={left:['IP-003','IP-004','IP-002','IP-005','IP-006','EP-010','EP-011','EP-008','EP-007'],bottom:['EP-040','IP-001','ARBURG'],right:['IP-032','IP-035','IP-039','EP-038','EP-048','IP-040','IP-034','EP-041']};
type Zone='left'|'right'|'bottom'; type Layout=typeof defaultLayout;
export default function OperationsDashboard(){
 const [layout,setLayout]=useState<Layout>(defaultLayout),[programs,setPrograms]=useState<Program[]>([]),[orders,setOrders]=useState<Order[]>([]),[allocs,setAllocs]=useState<Allocation[]>([]),[prod,setProd]=useState<Production[]>([]),[edit,setEdit]=useState(false),[drag,setDrag]=useState('');
 const load=()=>{setPrograms(read(KEYS.programs,[]));setOrders(read(KEYS.orders,[]));setAllocs(read(KEYS.allocations,[]));setProd(read(KEYS.production,[]));try{const x=localStorage.getItem('anclo-layout-v1');if(x)setLayout(JSON.parse(x))}catch{}};
 useEffect(()=>{load();addEventListener('anclo-operations-updated',load);addEventListener('storage',load);return()=>{removeEventListener('anclo-operations-updated',load);removeEventListener('storage',load)}},[]);
 const active=programs.find(p=>p.estado==='EN EJECUCIÓN')||programs.find(p=>p.estado==='LIBERADO');
 const pa=active?allocs.filter(a=>orders.some(o=>o.programId===active.id&&o.id===a.orderId)):[]; const sch=scheduleAllocations(pa,active);
 const info=(m:string)=>{const candidates=pa.filter(x=>x.maquina===m).sort((a,b)=>a.secuencia-b.secuencia);const a=candidates[0];if(!a)return null;const o=orders.find(x=>x.id===a.orderId);const logs=prod.filter(x=>x.allocationId===a.id);const made=logs.reduce((n,x)=>n+(x.piezas||0),0),sc=sch.find(x=>x.allocationId===a.id);const last=logs.at(-1);return {a,o,made,sc,last,logs}};
 const all=[...layout.left,...layout.bottom,...layout.right],programmed=all.filter(m=>info(m)).length,producing=all.filter(m=>{const i=info(m);return i&&i.made>0&&i.made<(i.a.cantidad||Infinity)}).length;
 const saveLayout=(l:Layout)=>{setLayout(l);localStorage.setItem('anclo-layout-v1',JSON.stringify(l));window.dispatchEvent(new Event('anclo-operations-updated'))};
 const drop=(z:Zone,before?:string)=>{if(!drag)return;const n:any={left:layout.left.filter(x=>x!==drag),right:layout.right.filter(x=>x!==drag),bottom:layout.bottom.filter(x=>x!==drag)};const a=n[z];const i=before?a.indexOf(before):-1;i>=0?a.splice(i,0,drag):a.push(drag);saveLayout(n);setDrag('')};
 const card=(m:string)=>{const i=info(m),mm=machineMaster.find(x=>x.numero===m),pct=i?.a.cantidad?Math.min(100,i.made/i.a.cantidad*100):0;const running=!!i&&i.made>0&&i.made<(i.a.cantidad||Infinity);const cls=!i?'estado-sin-plan':running?'estado-proceso':'estado-prep';return <button draggable={edit} onDragStart={()=>setDrag(m)} className={'machine-unit '+cls}>
  <div className="machine-art"><span className="hopper"/><span className="body"/><span className="base"/></div><div className="machine-info"><div className="machine-title"><b>{m} · {mm?.modelo||mm?.marca||''}</b></div>
  <span className={'machine-state '+(!i?'state-off':running?'state-run':'state-plan')}>{!i?'● SIN PLANEACIÓN':running?'● PRODUCIENDO':'● PROGRAMADA'}</span>
  {i?<><strong>{i.a.producto} · {i.a.molde}</strong><small>{i.o?.folioInterno}{i.o?.op?` · OP ${i.o.op}`:''}</small><div className="machine-progress"><i style={{width:`${pct}%`}}/></div><small><b>{i.made.toLocaleString()}</b> / {(i.a.cantidad||0).toLocaleString()} pzas · <b>{pct.toFixed(0)}%</b></small><small>Molde: {i.a.moldeDescripcion||'—'} · {i.a.cavidades??'—'} cav.</small>{i.last?.operadores&&<small>👤 {i.last.operadores}</small>}<small>⏱ {i.a.ciclo??'—'} s · {i.sc?.pzh?.toLocaleString()||'—'} pz/h</small><small>🏁 {i.sc?`Fin est. ${new Date(i.sc.end).toLocaleString('es-MX',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}`:'Fin pendiente'}</small></>:<small className="no-plan-text">Máquina sin trabajo asignado</small>}</div></button>};
 const zone=(z:Zone,cls:string)=><div className={'bank '+cls} onDragOver={e=>edit&&e.preventDefault()} onDrop={()=>drop(z)}>{layout[z].map(m=><div key={m} onDragOver={e=>edit&&e.preventDefault()} onDrop={e=>{if(edit){e.stopPropagation();drop(z,m)}}}>{card(m)}</div>)}</div>;
 return <><div className="top"><div><div className="title">Monitoreo de planta</div><div className="muted">{active?active.nombre:'Sin programa liberado'} · vinculado a Planeación y Producción</div></div><button className="btn secondary" onClick={()=>setEdit(v=>!v)}>{edit?'✓ Terminar edición':'✏ Editar planta'}</button></div>
 <div className="grid monitor-kpis"><div className="card"><div className="muted">Máquinas</div><div className="kpi">{all.length}</div></div><div className="card"><div className="muted">🟢 Produciendo</div><div className="kpi green">{producing}</div></div><div className="card"><div className="muted">🟡 Programadas</div><div className="kpi amber">{Math.max(0,programmed-producing)}</div></div><div className="card"><div className="muted">🔴 Sin planeación</div><div className="kpi red">{Math.max(0,all.length-programmed)}</div></div></div>
 <section className="section"><div className="section-title-row"><h2>Plano operativo</h2><div className="legend"><span className="lg ok">● Produciendo</span><span className="lg warn">● Programada</span><span className="lg bad">● Sin planeación</span></div></div><div className="plant-floor">{zone('left','left-bank')}<div className="aisle"><div className="aisle-label">PASILLO CENTRAL</div><div className="entrance">ENTRADA</div></div>{zone('right','right-bank')}<div className="bottom-bank">{layout.bottom.map(m=><div key={m}>{card(m)}</div>)}</div></div></section></>;
}
