'use client';
import {useEffect,useMemo,useState} from 'react';
import {machineMaster} from '@/lib/machines';
import {Allocation,KEYS,Order,Production,Program,read,realPiecesFor,scheduleAllocations,write} from '@/lib/operations';
import {QUALITY_KEYS,QualityRelease,qread,acceptedForAllocation} from '@/lib/quality';
import {displayQty,fmtQty,isCincho,naturalCompare,productionPieces} from '@/lib/display';
import {loadPersonnel} from '@/lib/personnel';
const defaultLayout={left:['IP-003','IP-004','IP-002','IP-005','IP-006','EP-010','EP-011','EP-008','EP-007'],bottom:['EP-040','IP-001','ARBURG'],right:['IP-032','IP-035','IP-039','EP-038','EP-048','IP-040','IP-034','EP-041']};
type Zone='left'|'right'|'bottom';type Layout=typeof defaultLayout;
const isoWeek=(value?:string)=>{if(!value)return '—';const d=new Date(`${value}T12:00:00`),u=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),day=u.getUTCDay()||7;u.setUTCDate(u.getUTCDate()+4-day);const y=new Date(Date.UTC(u.getUTCFullYear(),0,1));return String(Math.ceil((((u.getTime()-y.getTime())/86400000)+1)/7))};
export default function OperationsDashboard(){
 const [layout,setLayout]=useState<Layout>(defaultLayout),[programs,setPrograms]=useState<Program[]>([]),[orders,setOrders]=useState<Order[]>([]),[allocs,setAllocs]=useState<Allocation[]>([]),[prod,setProd]=useState<Production[]>([]),[quality,setQuality]=useState<QualityRelease[]>([]),[edit,setEdit]=useState(false),[drag,setDrag]=useState(''),[selected,setSelected]=useState(''),[mobileFilter,setMobileFilter]=useState('TODAS'),[reading,setReading]=useState(''),[ops,setOps]=useState<string[]>([]);
 const load=()=>{setPrograms(read(KEYS.programs,[]));setOrders(read(KEYS.orders,[]));setAllocs(read(KEYS.allocations,[]));setProd(read(KEYS.production,[]));setQuality(qread(QUALITY_KEYS.releases,[]));try{const x=localStorage.getItem('anclo-layout-v1');if(x)setLayout(JSON.parse(x))}catch{}};
 useEffect(()=>{load();addEventListener('anclo-operations-updated',load);return()=>removeEventListener('anclo-operations-updated',load)},[]);
 const active=programs.find(p=>p.estado==='EN EJECUCIÓN')||programs.find(p=>p.estado==='LIBERADO'),activeOrders=active?orders.filter(o=>o.programId===active.id):[],pa=active?allocs.filter(a=>activeOrders.some(o=>o.id===a.orderId)):[],sch=scheduleAllocations(pa,active);
 const info=(m:string)=>{const candidates=pa.filter(x=>x.maquina===m),a=candidates.find(x=>acceptedForAllocation(x.id,quality,x.producto)<realPiecesFor(x))||candidates[0];if(!a)return null;const o=orders.find(x=>x.id===a.orderId);const produced=prod.filter(x=>x.allocationId===a.id).reduce((n,x)=>n+productionPieces(x,x.piezas||0,a.producto),0),accepted=acceptedForAllocation(a.id,quality,a.producto),hasQuality=quality.some(x=>x.allocationId===a.id&&x.estado!=='ANULADA'),made=hasQuality?accepted:produced,operators=[...new Set(prod.filter(x=>x.allocationId===a.id).flatMap(x=>(x.operadores||'').split(',').map(v=>v.trim()).filter(Boolean)))],sc=sch.find(x=>x.allocationId===a.id);return {a,o,made,produced,accepted,operators,sc,queue:candidates}};
 const weekly=useMemo(()=>{const map=new Map<string,{product:string,target:number;accepted:number}>();pa.forEach(a=>{const product=a.producto||'Sin producto',x=map.get(product)||{product,target:0,accepted:0};x.target+=realPiecesFor(a);x.accepted+=acceptedForAllocation(a.id,quality,product);map.set(product,x)});return [...map.values()].map(x=>({...x,missing:Math.max(0,x.target-x.accepted),excess:Math.max(0,x.accepted-x.target),pct:x.target?x.accepted/x.target*100:0})).sort((a,b)=>naturalCompare(a.product,b.product))},[pa,quality]);
 const hlr=weekly.filter(x=>/^HLR/i.test(x.product)),totals=weekly.reduce((a,x)=>({missing:a.missing+x.missing,excess:a.excess+x.excess}),{missing:0,excess:0});
 const saveReading=(m:string)=>{const i=info(m),n=Number(reading);if(!i||!n)return;const last=i.produced,delta=Math.max(0,(isCincho(i.a.producto)?n*100:n)-last);if(!delta){alert('La lectura no supera el acumulado reportado.');return}const p:Production={id:crypto.randomUUID(),allocationId:i.a.id,orderId:i.a.orderId,fecha:new Date().toISOString().slice(0,10),hora:new Date().toTimeString().slice(0,5),turno:new Date().getHours()<19?'DÍA':'NOCHE',operadores:ops.join(', '),kg:null,piezas:delta,unidadCaptura:isCincho(i.a.producto)?'BOLSAS':'PIEZAS',ciclo:i.a.ciclo,cavidades:i.a.cavidades,merma:null,purga:null,horas:null,resultado:'PRODUJO',motivo:'',comentario:'Lectura rápida desde Monitoreo',maquinaReal:m,moldeReal:i.a.molde};write(KEYS.production,[...prod,p]);setReading('');load()};
 const card=(m:string)=>{const i=info(m),mm=machineMaster.find(x=>x.numero===m),target=i?realPiecesFor(i.a):0,pct=i&&target?i.made/target*100:0,missing=i?Math.max(0,target-i.made):0,excess=i?Math.max(0,i.made-target):0;return <button onClick={()=>!edit&&setSelected(m)} draggable={edit} onDragStart={()=>setDrag(m)} className={'machine-unit '+(i?(i.made>0?'estado-proceso':'estado-prep'):'estado-idle')}><div className="machine-art"><span className="hopper"/><span className="body"/><span className="base"/></div><div className="machine-info"><b>{m} · {mm?.modelo||mm?.marca||''}</b><span>{i?(i.made>0?'PRODUCIENDO':'PROGRAMADA'):'SIN PROGRAMA'}</span>{i?<><strong>{i.a.producto} · {i.a.molde}</strong><small>📦 {fmtQty(i.made,i.a.producto)} / {fmtQty(target,i.a.producto)} · {pct.toFixed(1)}%</small><span className="machine-progress"><i style={{width:`${Math.min(100,pct)}%`}}/></span><small className={excess?'monitor-excess':missing?'monitor-missing':'monitor-done'}>{excess?`▲ Excedente +${fmtQty(excess,i.a.producto)}`:missing?`▼ Faltan ${fmtQty(missing,i.a.producto)}`:'✓ Cumplido'}</small><small>👤 {i.operators.length?i.operators.slice(0,3).join(' / '):'Operador pendiente'}</small></>:<small>Sin OP registrada</small>}</div></button>};
 const zone=(z:Zone,cls:string)=><div className={'bank '+cls}>{layout[z].map(m=><div key={m}>{card(m)}</div>)}</div>;
 const si=selected?info(selected):null,people=loadPersonnel().filter(x=>x.activo).sort((a,b)=>Number(a.numero)-Number(b.numero));
 return <><div className="top"><div><div className="title">Monitoreo de planta</div><div className="muted"><b>Semana {isoWeek(active?.fechaInicio)}</b> · {active?.fechaInicio||'—'} → {active?.fechaFin||'—'}</div></div><button className="btn secondary" onClick={()=>setEdit(v=>!v)}>{edit?'✓ Terminar edición':'✏ Editar planta'}</button></div>
 <div className="mobile-monitor-filters"><button onClick={()=>setMobileFilter('TODAS')}>Todas</button><button onClick={()=>setMobileFilter('PRODUCIENDO')}>Produciendo</button><button onClick={()=>setMobileFilter('PROGRAMADA')}>Programadas</button><button onClick={()=>setMobileFilter('SIN PROGRAMA')}>Sin programa</button></div>
 <section className="section desktop-plant"><div className="plant-floor">{zone('left','left-bank')}<div className="aisle"><div className="entrance">ENTRADA</div><div className="aisle-label">PASILLO CENTRAL</div></div>{zone('right','right-bank')}<div className="bottom-bank">{layout.bottom.map(m=><div key={m}>{card(m)}</div>)}</div></div></section>
 <section className="mobile-machine-list">{[...layout.left,...layout.right,...layout.bottom].filter(m=>{const i=info(m),st=i?(i.made?'PRODUCIENDO':'PROGRAMADA'):'SIN PROGRAMA';return mobileFilter==='TODAS'||st===mobileFilter}).map(m=><div key={m}>{card(m)}</div>)}</section>
 <section className="section weekly-monitor"><h2>Producción vs programa · Semana {isoWeek(active?.fechaInicio)}</h2><div className="weekly-product-grid">{weekly.map(x=><article className="weekly-product-card" key={x.product}><div><b>{x.product}</b><span>{x.pct.toFixed(1)}%</span></div><small>Programado {fmtQty(x.target,x.product)} · Aceptado {fmtQty(x.accepted,x.product)}</small><div className="weekly-bar"><i style={{width:`${Math.min(100,x.pct)}%`}}/></div><strong>{x.excess?`Excedente +${fmtQty(x.excess,x.product)}`:x.missing?`Faltan ${fmtQty(x.missing,x.product)}`:'Cumplido ✓'}</strong></article>)}</div></section>
 {hlr.length>0&&<section className="section"><h2>Avance HLR</h2><div className="hlr-grid">{hlr.map(x=><article className="hlr-card" key={x.product}><div><b>{x.product}</b><strong>{x.pct.toFixed(1)}%</strong></div><small>{fmtQty(x.accepted,x.product)} / {fmtQty(x.target,x.product)}</small></article>)}</div></section>}
 {selected&&<div className="machine-modal" onClick={()=>setSelected('')}><div className="machine-modal-card" onClick={e=>e.stopPropagation()}><div className="section-title-row"><h2>{selected} · Operación en planta</h2><button onClick={()=>setSelected('')}>✕</button></div>{si?<><div className="machine-live"><b>{si.a.producto} · {si.a.molde}</b><span>{fmtQty(si.produced,si.a.producto)} reportadas · {fmtQty(si.accepted,si.a.producto)} liberadas</span></div><label>Lectura acumulada actual ({isCincho(si.a.producto)?'bolsas de 100':'piezas'})<input type="number" value={reading} onChange={e=>setReading(e.target.value)} placeholder={String(displayQty(si.produced,si.a.producto))}/></label><div className="operator-checks"><b>Personal actual · hasta 3</b>{people.map(p=><label key={p.id}><input type="checkbox" checked={ops.includes(p.nombre)} disabled={!ops.includes(p.nombre)&&ops.length>=3} onChange={e=>setOps(v=>e.target.checked?[...v,p.nombre]:v.filter(x=>x!==p.nombre))}/>{p.numero} · {p.nombre}</label>)}</div><button className="btn" onClick={()=>saveReading(selected)}>Guardar lectura de producción</button><div className="machine-actions"><a href="/incidencias">⚠ Registrar paro / incidencia</a><a href="/planeacion">📋 Ver / reprogramar cola</a></div><h3>Cola de producción</h3>{si.queue.map((a,k)=><div className="queue-row" key={a.id}><b>{k===0?'Actual':'Siguiente '+k}</b><span>{a.producto} · {a.molde} · {fmtQty(realPiecesFor(a),a.producto)}</span></div>)}</>:<p>Sin programa. Puedes consultar Planeación o registrar una incidencia.</p>}</div></div>}
 </>;
}
