'use client';
import {useMemo,useState} from 'react';
import {processStandards} from '@/lib/processCatalog';
const shortMold=(s:string)=>s.split('-MOLDE')[0].split('-ESQUINERO')[0].trim();
export default function Page(){
 const [q,setQ]=useState(''),[selected,setSelected]=useState('');
 const molds=useMemo(()=>{const m=new Map<string,typeof processStandards>();for(const r of processStandards){const k=shortMold(r.herramental);m.set(k,[...(m.get(k)||[]),r])}return [...m.entries()].map(([id,rs])=>({id,desc:rs[0].herramental,rs,machines:new Set(rs.map(x=>x.maquina)).size,products:new Set(rs.map(x=>x.producto)).size})).sort((a,b)=>a.id.localeCompare(b.id))},[]);
 const shown=molds.filter(x=>`${x.id} ${x.desc}`.toLowerCase().includes(q.toLowerCase())); const cur=molds.find(x=>x.id===selected)||shown[0];
 return <><div className="top"><div><div className="title">Moldes / Herramientas</div><div className="muted">Compatibilidad máquina–molde, productos y estándares de ciclo</div></div><span className="count">{molds.length} herramientas</span></div>
 <div className="catalog-layout"><section className="card"><input className="catalog-search" placeholder="🔎 Buscar molde o herramienta" value={q} onChange={e=>setQ(e.target.value)}/><div className="catalog-list">{shown.map(x=><button key={x.id} className={cur?.id===x.id?'catalog-item active':'catalog-item'} onClick={()=>setSelected(x.id)}><b>{x.id}</b><span>{x.desc}</span><small>{x.machines} máquinas · {x.products} productos</small></button>)}</div></section>
 {cur&&<section className="card catalog-detail"><div className="detail-head"><div><h2>{cur.id}</h2><div className="muted">{cur.desc}</div></div><span className="status ok">ACTIVO</span></div><div className="grid mini-kpis"><div><small>Máquinas compatibles</small><b>{cur.machines}</b></div><div><small>Productos</small><b>{cur.products}</b></div><div><small>Registros de proceso</small><b>{cur.rs.length}</b></div></div><h3>Estándares por máquina y producto</h3><div className="table-wrap"><table className="process-table"><thead><tr><th>Máquina</th><th>Producto</th><th>Ciclo teórico</th><th>Cavidades</th><th>Pz/ciclo</th><th>Cap. calculada</th><th>Pz/h fuente</th></tr></thead><tbody>{cur.rs.map((r,i)=>{const calc=r.ciclo_s&&r.pz_ciclo?3600/r.ciclo_s*r.pz_ciclo:null;return <tr key={`${r.maquina}-${r.producto}-${i}`}><td><b>{r.maquina}</b></td><td>{r.producto}</td><td><b>{r.ciclo_s??'—'} s</b></td><td>{r.cavidades??'—'}</td><td>{r.pz_ciclo??'—'}</td><td>{calc?Math.round(calc).toLocaleString():'—'} pz/h</td><td>{r.pz_hora_fuente?.toLocaleString()??'—'}</td></tr>})}</tbody></table></div><div className="info-strip demo-note">El Gantt usa <b>ciclo teórico + piezas por ciclo</b> de la combinación exacta Molde + Máquina + Producto. El valor “Pz/h fuente” se conserva para auditoría.</div></section>}</div></>}
