'use client';
import {useEffect,useMemo,useState} from 'react';
import {loadProcessStandards,ProcessStandard,saveProcessOverride} from '@/lib/processRuntime';
const shortMold=(s:string)=>s.split('-MOLDE')[0].split('-ESQUINERO')[0].trim();
export default function Page(){
 const [q,setQ]=useState(''),[selected,setSelected]=useState(''),[standards,setStandards]=useState<ProcessStandard[]>([]),[editing,setEditing]=useState<string|null>(null);
 const reload=()=>setStandards(loadProcessStandards()); useEffect(()=>{reload();window.addEventListener('anclo-process-updated',reload);return()=>window.removeEventListener('anclo-process-updated',reload)},[]);
 const molds=useMemo(()=>{const m=new Map<string,ProcessStandard[]>();for(const r of standards){const k=shortMold(r.herramental);m.set(k,[...(m.get(k)||[]),r])}return [...m.entries()].map(([id,rs])=>({id,desc:rs[0].herramental,rs,machines:new Set(rs.map(x=>x.maquina)).size,products:new Set(rs.map(x=>x.producto)).size})).sort((a,b)=>a.id.localeCompare(b.id))},[standards]);
 const shown=molds.filter(x=>`${x.id} ${x.desc}`.toLowerCase().includes(q.toLowerCase())); const cur=molds.find(x=>x.id===selected)||shown[0];
 const key=(r:ProcessStandard,i:number)=>`${r.herramental}|${r.maquina}|${r.producto}|${i}`;
 const edit=(r:ProcessStandard,i:number,k:keyof ProcessStandard,v:any)=>{saveProcessOverride(r,{[k]:v} as any);reload();setEditing(key({...r,[k]:v} as ProcessStandard,i))};
 return <><div className="top"><div><div className="title">Moldes / Herramientas</div><div className="muted">Compatibilidad máquina–molde, productos y estándares editables de proceso</div></div><span className="count">{molds.length} herramientas</span></div>
 <div className="catalog-layout"><section className="card"><input className="catalog-search" placeholder="🔎 Buscar molde o herramienta" value={q} onChange={e=>setQ(e.target.value)}/><div className="catalog-list">{shown.map(x=><button key={x.id} className={cur?.id===x.id?'catalog-item active':'catalog-item'} onClick={()=>setSelected(x.id)}><b>{x.id}</b><span>{x.desc}</span><small>{x.machines} máquinas · {x.products} productos</small></button>)}</div></section>
 {cur&&<section className="card catalog-detail"><div className="detail-head"><div><h2>{cur.id}</h2><div className="muted">{cur.desc}</div></div><span className="status ok">ACTIVO</span></div><div className="grid mini-kpis"><div><small>Máquinas compatibles</small><b>{cur.machines}</b></div><div><small>Productos</small><b>{cur.products}</b></div><div><small>Registros de proceso</small><b>{cur.rs.length}</b></div></div><div className="section-title-row"><h3>Estándares por máquina y producto</h3><span className="muted small">✏ Edita una fila para corregir errores de captura. Capacidad se recalcula sola.</span></div><div className="table-wrap"><table className="process-table"><thead><tr><th>Máquina</th><th>Producto</th><th>Ciclo teórico</th><th>Cavidades</th><th>Pz/ciclo</th><th>Cap. calculada</th><th>Pz/h fuente</th><th></th></tr></thead><tbody>{cur.rs.map((r,i)=>{const k=key(r,i),is=editing===k,calc=r.ciclo_s&&r.pz_ciclo?3600/r.ciclo_s*r.pz_ciclo:null;return <tr key={k}><td><b>{r.maquina}</b></td><td>{r.producto}</td><td>{is?<input className="cell mini" type="number" step="0.1" value={r.ciclo_s??''} onChange={e=>edit(r,i,'ciclo_s',e.target.value?Number(e.target.value):null)}/>:<b>{r.ciclo_s??'—'} s</b>}</td><td>{is?<input className="cell mini" type="number" value={r.cavidades??''} onChange={e=>edit(r,i,'cavidades',e.target.value?Number(e.target.value):null)}/>:r.cavidades??'—'}</td><td>{is?<input className="cell mini" type="number" value={r.pz_ciclo??''} onChange={e=>edit(r,i,'pz_ciclo',e.target.value?Number(e.target.value):null)}/>:r.pz_ciclo??'—'}</td><td><b>{calc?Math.round(calc).toLocaleString():'—'} pz/h</b></td><td>{r.pz_hora_fuente?.toLocaleString()??'—'}</td><td><button className="view-btn" onClick={()=>setEditing(is?null:k)}>{is?'✓ Listo':'✏ Editar'}</button></td></tr>})}</tbody></table></div><div className="info-strip demo-note">El Gantt usa <b>ciclo teórico + piezas por ciclo</b> de la combinación exacta Molde + Máquina + Producto. Las correcciones se aplican a planeaciones nuevas; “Pz/h fuente” se conserva como referencia.</div></section>}</div></>}
