'use client';
import {useEffect,useMemo,useState} from 'react';
import {Allocation,KEYS,Order,Production,Program,read} from '@/lib/operations';
export default function Page(){
 const [programs,setPrograms]=useState<Program[]>([]),[orders,setOrders]=useState<Order[]>([]),[allocs,setAllocs]=useState<Allocation[]>([]),[prod,setProd]=useState<Production[]>([]),[date,setDate]=useState(new Date().toISOString().slice(0,10));
 const load=()=>{setPrograms(read(KEYS.programs,[]));setOrders(read(KEYS.orders,[]));setAllocs(read(KEYS.allocations,[]));setProd(read(KEYS.production,[]))};useEffect(()=>{load();window.addEventListener('anclo-operations-updated',load);return()=>window.removeEventListener('anclo-operations-updated',load)},[]);
 const rows=useMemo(()=>allocs.map(a=>{const o=orders.find(x=>x.id===a.orderId);if(!o)return null;const today=prod.filter(x=>x.allocationId===a.id&&x.fecha===date);const day=today.filter(x=>x.turno==='DÍA').reduce((n,x)=>n+(x.piezas||0),0),night=today.filter(x=>x.turno==='NOCHE').reduce((n,x)=>n+(x.piezas||0),0);const opProd=prod.filter(x=>x.orderId===o.id).reduce((n,x)=>n+(x.piezas||0),0);return {a,o,day,night,total:day+night,opProd,remaining:Math.max(0,(o.cantidad||0)-opProd),advance:o.cantidad?opProd/o.cantidad*100:0}}).filter((x):x is NonNullable<typeof x>=>!!x&&x.total>0),[allocs,orders,prod,date]);
 const csv=()=>{const t=document.querySelector('table');if(!t)return;const lines=Array.from(t.querySelectorAll('tr')).map(tr=>Array.from(tr.querySelectorAll('th,td')).map(c=>'"'+(c.textContent||'').replaceAll('"','""')+'"').join(','));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv'}));a.download=`concentrado-${date}.csv`;a.click()};
 return <><div className="top"><div><div className="title">Concentrado diario</div><div className="muted">Datos reales registrados en Producción Día / Noche</div></div><div className="actions"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="btn secondary" onClick={csv}>Descargar CSV</button></div></div><section className="section"><div className="table-wrap"><table><thead><tr><th>Máquina</th><th>OP</th><th>Producto / Clave</th><th>Molde</th><th>Meta OP</th><th>Día pzas</th><th>Noche pzas</th><th>Total día</th><th>Acumulado OP</th><th>Faltan</th><th>Avance</th><th>MP liberada kg</th><th>Reciclado kg</th><th>Pigmento kg</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={14} className="muted">No hay producción real registrada para {date}. El concentrado ya no contiene datos demostrativos.</td></tr>:rows.map(x=><tr key={x.a.id}><td><b>{x.a.maquina}</b></td><td>{x.o.op}</td><td>{x.o.producto}</td><td>{x.a.molde}</td><td>{x.o.cantidad?.toLocaleString()||'—'}</td><td>{x.day.toLocaleString()}</td><td>{x.night.toLocaleString()}</td><td><b>{x.total.toLocaleString()}</b></td><td>{x.opProd.toLocaleString()}</td><td>{x.remaining.toLocaleString()}</td><td>{x.advance.toFixed(1)}%</td><td>{x.o.virgenKg??'—'}</td><td>{x.o.recicladoKg??'—'}</td><td>{x.o.pigmentoKg??'—'}</td></tr>)}</tbody></table></div></section></>}
