'use client';
import {useEffect,useMemo,useState} from 'react';
import {loadProducts,ProductMaster,saveProduct} from '@/lib/products';
const empty:ProductMaster={clave:'',descripcion:'',familia:'GENERAL',unidad:'PZA',requiereTension:false,activo:true,custom:true};
export default function ProductosPage(){
 const [items,setItems]=useState<ProductMaster[]>([]),[q,setQ]=useState(''),[draft,setDraft]=useState<ProductMaster>(empty),[original,setOriginal]=useState('');
 const load=()=>setItems(loadProducts()); useEffect(()=>{load();addEventListener('anclo-products-updated',load);addEventListener('anclo-process-updated',load);return()=>{removeEventListener('anclo-products-updated',load);removeEventListener('anclo-process-updated',load)}},[]);
 const shown=useMemo(()=>items.filter(x=>`${x.clave} ${x.descripcion} ${x.familia}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
 const edit=(p:ProductMaster)=>{setDraft({...p});setOriginal(p.clave)};
 const save=()=>{if(!draft.clave.trim()||!draft.descripcion.trim())return alert('Captura clave y descripción.');saveProduct(draft,original||undefined);setDraft(empty);setOriginal('');load()};
 return <><div className="top"><div><div className="title">Productos</div><div className="muted">Maestro único de claves de producto para Planeación, Moldes, Producción y Calidad.</div></div><div className="actions"><span className="count">{items.filter(x=>x.activo).length} activos</span></div></div>
 <section className="section"><h3>{original?'Editar producto':'Alta de producto'}</h3><div className="form-4"><label>Clave<input value={draft.clave} onChange={e=>setDraft({...draft,clave:e.target.value.toUpperCase()})} placeholder="AG14"/></label><label>Descripción<input value={draft.descripcion} onChange={e=>setDraft({...draft,descripcion:e.target.value})}/></label><label>Familia<select value={draft.familia} onChange={e=>setDraft({...draft,familia:e.target.value})}><option>GENERAL</option><option>CINCHO / COMPONENTE</option><option>HLR</option><option>OTRO</option></select></label><label>Unidad<select value={draft.unidad} onChange={e=>setDraft({...draft,unidad:e.target.value})}><option>PZA</option><option>KG</option></select></label><label><input type="checkbox" checked={draft.requiereTension} onChange={e=>setDraft({...draft,requiereTension:e.target.checked})}/> Requiere estudio de tensión</label><label><input type="checkbox" checked={draft.activo} onChange={e=>setDraft({...draft,activo:e.target.checked})}/> Producto activo</label></div><div className="actions"><button className="btn" onClick={save}>Guardar producto</button>{original&&<button className="btn secondary" onClick={()=>{setDraft(empty);setOriginal('')}}>Cancelar</button>}</div></section>
 <section className="section"><input className="catalog-search" placeholder="🔎 Buscar clave o descripción" value={q} onChange={e=>setQ(e.target.value)}/><div className="table-wrap"><table className="process-table"><thead><tr><th>Clave</th><th>Descripción</th><th>Familia</th><th>Unidad</th><th>Tensión</th><th>Estado</th><th></th></tr></thead><tbody>{shown.map(p=><tr key={p.clave}><td><b>{p.clave}</b></td><td>{p.descripcion}</td><td>{p.familia}</td><td>{p.unidad}</td><td>{p.requiereTension?'Sí':'No'}</td><td><span className={p.activo?'status ok':'status'}>{p.activo?'ACTIVO':'INACTIVO'}</span></td><td><button className="view-btn" onClick={()=>edit(p)}>✏ Editar</button></td></tr>)}</tbody></table></div><div className="info-strip demo-note">Las claves existentes se cargan automáticamente desde el maestro de procesos. No necesitas volver a capturarlas. Los productos inactivos conservan su historial, pero dejan de aparecer para nuevas configuraciones.</div></section></>;
}
