'use client';
import {useEffect,useMemo,useState} from 'react';
import {KEYS,Allocation,Order,read,realPiecesFor} from '@/lib/operations';
import {QUALITY_KEYS,QualityRelease,acceptedForAllocation,qread,qualityPdfLines} from '@/lib/quality';
import {downloadSimplePdf} from '@/lib/simplePdf';
import {fmtQty,naturalCompare} from '@/lib/display';
export default function Historial(){
 const [rows,setRows]=useState<QualityRelease[]>([]),[allocs,setAllocs]=useState<Allocation[]>([]),[orders,setOrders]=useState<Order[]>([]),[fecha,setFecha]=useState(''),[resultado,setResultado]=useState('');
 useEffect(()=>{setRows(qread(QUALITY_KEYS.releases,[]));setAllocs(read(KEYS.allocations,[]));setOrders(read(KEYS.orders,[]));const p=new URLSearchParams(window.location.search);setFecha(p.get('fecha')||'');setResultado(p.get('resultado')||'')},[]);
 const visible=useMemo(()=>rows.filter(r=>(!fecha||r.fecha.slice(0,10)===fecha)&&(!resultado||r.resultado===resultado)).sort((a,b)=>{const aa=allocs.find(x=>x.id===a.allocationId),bb=allocs.find(x=>x.id===b.allocationId);return naturalCompare(aa?.producto||'',bb?.producto||'')||(a.fecha||'').localeCompare(b.fecha||'')}),[rows,allocs,fecha,resultado]);
 return <><div className="top"><div><div className="title">Historial de Calidad</div><div className="muted">Trazabilidad de liberaciones, cambios de máquina/molde y revisiones.{fecha?` · ${fecha}`:''}{resultado?` · ${resultado}`:''}</div></div><a className="view-btn" href="/calidad/historial">Quitar filtros</a></div><section className="section"><div className="table-wrap"><table className="quality-history-table"><thead><tr><th>Folio</th><th>Fecha</th><th>Máquina real</th><th>OP</th><th>Producto</th><th>Molde real</th><th>Turno</th><th>Reportadas</th><th>Aceptadas</th><th>Rech.</th><th>Avance</th><th>Estado</th><th>Responsable</th><th>PDF</th></tr></thead><tbody>{visible.map(r=>{const a=allocs.find(x=>x.id===r.allocationId),o=orders.find(x=>x.id===r.orderId);return <tr key={r.id} className={r.estado==='ANULADA'?'row-annulled':''}><td>{r.pdfFolio}{(r.revision||0)>0?<small> Rev.{r.revision}</small>:''}</td><td>{new Date(r.fecha).toLocaleString('es-MX')}</td><td>{r.maquinaReal||r.maquinaPlaneada||a?.maquina||'—'}</td><td>{o?.op||o?.folioInterno||'—'}</td><td>{a?.producto||'—'}</td><td>{r.moldeReal||r.moldePlaneado||a?.molde||'—'}</td><td>{r.turno||'—'}</td><td>{fmtQty(r.piezasReportadas,a?.producto||'')}</td><td>{fmtQty(r.piezasAceptadas,a?.producto||'')}</td><td>{fmtQty(r.piezasRechazadas,a?.producto||'')}</td><td>{fmtQty(acceptedForAllocation(r.allocationId,rows,a?.producto),a?.producto||'')} / {a?fmtQty(realPiecesFor(a),a.producto):'—'}</td><td>{r.estado==='ANULADA'?'ANULADA':r.resultado}</td><td>{r.responsable}</td><td><button className="view-btn" onClick={()=>downloadSimplePdf(`${r.pdfFolio}.pdf`,'ANCLO PLASTICOS - LIBERACION DE CALIDAD',qualityPdfLines(r,{producto:a?.producto,op:o?.op||o?.folioInterno}))}>PDF</button></td></tr>})}</tbody></table></div></section></>}
