'use client';
import {useEffect,useMemo,useState} from 'react';
import {Allocation,KEYS,Order,Production,read} from '@/lib/operations';
import {QUALITY_KEYS,TensionStudy,qread,qwrite,samplingPlan,tensionIdentity} from '@/lib/quality';
import {initialPersonnel} from '@/lib/personnel';
import {downloadSimplePdf} from '@/lib/simplePdf';

const week=(d:string)=>{const x=new Date(d+'T12:00:00');const z=new Date(x.getFullYear(),0,1);return Math.ceil((((x.getTime()-z.getTime())/86400000)+z.getDay()+1)/7)};
export default function Tension(){
 const [rows,setRows]=useState<TensionStudy[]>([]),[allocs,setAllocs]=useState<Allocation[]>([]),[orders,setOrders]=useState<Order[]>([]),[prod,setProd]=useState<Production[]>([]);
 const [source,setSource]=useState(''),[producto,setProducto]=useState(''),[lote,setLote]=useState(''),[maquina,setMaquina]=useState(''),[molde,setMolde]=useState(''),[cav,setCav]=useState(4),[qty,setQty]=useState(1000),[virgen,setVirgen]=useState(100),[ops,setOps]=useState<string[]>([]),[coord,setCoord]=useState(''),[active,setActive]=useState(''),[force,setForce]=useState(''),[failCavity,setFailCavity]=useState(1),[sampleObs,setSampleObs]=useState('');
 const load=()=>{setRows(qread(QUALITY_KEYS.tension,[]));setAllocs(read(KEYS.allocations,[]));setOrders(read(KEYS.orders,[]));setProd(read(KEYS.production,[]))};useEffect(()=>{load();addEventListener('anclo-operations-updated',load);return()=>removeEventListener('anclo-operations-updated',load)},[]);
 const candidates=useMemo(()=>prod.filter(p=>p.resultado==='PRODUJO').map(p=>{const a=allocs.find(x=>x.id===p.allocationId),o=orders.find(x=>x.id===p.orderId);return {p,a,o}}).filter(x=>x.a&&x.o&&/ACT|ACN/i.test(x.a!.producto)),[prod,allocs,orders]);
 const identity=tensionIdentity(producto),spec=identity.spec,sp=samplingPlan(qty); const current=rows.find(r=>r.id===active); const samples=current?.muestras||[]; const failures=samples.filter(x=>x.resultado==='NO PASA').length; const average=samples.length?samples.reduce((n,x)=>n+x.fuerzaN,0)/samples.length:0;
 const preload=(id:string)=>{setSource(id);const c=candidates.find(x=>x.p.id===id);if(!c||!c.a||!c.o)return;setProducto(c.a.producto);setMaquina(c.a.maquina);setMolde(c.a.molde);setCav(c.p.cavidades||c.a.cavidades||4);setQty(c.p.piezas||c.a.cantidad||1000);setOps((c.p.operadores||'').split(',').map(x=>x.trim()).filter(Boolean));};
 const create=()=>{if(!producto||!lote||!molde||!spec)return;const c=candidates.find(x=>x.p.id===source);const now=new Date();const r:TensionStudy={id:crypto.randomUUID(),allocationId:c?.a?.id,orderId:c?.o?.id,productionId:c?.p.id,folio:`TEN-${now.getFullYear()}-${String(rows.length+1).padStart(5,'0')}`,producto:identity.familia,productoVercel:producto,destino:identity.destino,color:identity.color,lote,maquina,molde,cavidades:cav,cantidad:qty,virgenPct:virgen,molidoPct:100-virgen,operadores:ops,coordinador:coord,fecha:now.toISOString(),fechaFabricacion:now.toISOString().slice(0,10),semanaProduccion:week(now.toISOString().slice(0,10)),fuerzaMinN:spec.n,fuerzaKgf:spec.kgf,tamanoNominalMm:spec.nominal,largoAMm:spec.largo,anchoBMm:spec.ancho,espesorCMm:spec.espesor,diametroAtadoEMm:spec.diametro,codigoMuestreo:sp.codigo,tamanoMuestra:sp.muestra,aceptar:sp.aceptar,rechazar:sp.rechazar,bolsas:sp.bolsas,muestras:[],estado:'EN CAPTURA',observaciones:''};const next=[r,...rows];qwrite(QUALITY_KEYS.tension,next);setRows(next);setActive(r.id)};
 const update=(r:TensionStudy)=>{const next=rows.map(x=>x.id===r.id?r:x);qwrite(QUALITY_KEYS.tension,next);setRows(next)};
 const addSample=()=>{if(!current)return;const f=Number(force);if(!Number.isFinite(f)||f<=0)return;const result=f>=current.fuerzaMinN?'PASA':'NO PASA';const s={numero:samples.length+1,fuerzaN:f,resultado:result as 'PASA'|'NO PASA',...(result==='NO PASA'?{cavidad:failCavity}:{}),observaciones:sampleObs||undefined};const ns=[...samples,s];const fails=ns.filter(x=>x.resultado==='NO PASA').length;const done=ns.length>=(current.tamanoMuestra||0)||fails>=(current.rechazar||999);update({...current,muestras:ns,estado:done?'TERMINADO':'EN CAPTURA'});setForce('');setSampleObs('')};
 const pdf=(r:TensionStudy)=>{const failBy=new Map<number,number>();r.muestras.filter(x=>x.resultado==='NO PASA'&&x.cavidad).forEach(x=>failBy.set(x.cavidad!,1+(failBy.get(x.cavidad!)||0)));downloadSimplePdf(`${r.folio}.pdf`,'ANCLO PLASTICOS - ESTUDIO DE TENSION',[`Folio: ${r.folio}`,`Clave Vercel: ${r.productoVercel||r.producto}`,`Destino: ${r.destino||'--'}`,`Color: ${r.color||'--'}`,`Lote: ${r.lote}`,`Maquina: ${r.maquina}`,`Molde: ${r.molde} · ${r.cavidades} cavidades`,`Produccion: ${r.cantidad.toLocaleString()} pzas`,`Mezcla: ${r.virgenPct}% virgen + ${r.molidoPct}% molido`,`Fuerza minima: ${r.fuerzaMinN.toFixed(2)} N (${r.fuerzaKgf||'--'} kgf)`,`Plan: ${r.codigoMuestreo} · muestra ${r.tamanoMuestra} · Ac ${r.aceptar} / Re ${r.rechazar}`,`Muestras realizadas: ${r.muestras.length}`,`Cumplen: ${r.muestras.filter(x=>x.resultado==='PASA').length}`,`No cumplen: ${r.muestras.filter(x=>x.resultado==='NO PASA').length}`,`Promedio: ${r.muestras.length?(r.muestras.reduce((n,x)=>n+x.fuerzaN,0)/r.muestras.length).toFixed(2):'--'} N`,`Fallas por cavidad: ${[...failBy].map(([c,n])=>`Cav. ${c}: ${n}`).join(' · ')||'Ninguna'}`,`Operadores: ${r.operadores.join(' / ')||'--'}`,`Coordinador: ${r.coordinador||'--'}`,`Estado: ${r.estado}`])};
 return <><div className="top"><div><div className="title">Estudios de tensión</div><div className="muted">Misma lógica útil de Streamlit, integrada a Producción. Vercel conserva la clave maestra: PRO = SUCURSAL · PRO A = HOME DEPOT.</div></div></div>
 <section className="section"><h2>⚡ Carga rápida desde Producción</h2><label>Producción de cincho<select value={source} onChange={e=>preload(e.target.value)}><option value="">Captura manual / seleccionar producción</option>{candidates.map(({p,a,o})=><option key={p.id} value={p.id}>{a!.maquina} · {a!.producto} · {o!.folioInterno} · {p.piezas?.toLocaleString()} pzas · {p.turno}</option>)}</select></label><p className="muted">Al seleccionarla se cargan producto, máquina, molde, cavidades, cantidad y operadores reales. Si faltan operadores, se agregan aquí.</p></section>
 <section className="section"><h2>Nuevo estudio</h2><div className="quality-form-grid"><label>Clave Vercel<input value={producto} onChange={e=>setProducto(e.target.value)} placeholder="Ej. ACN300-4 PRO A"/></label><label>Destino<input disabled value={identity.destino}/></label><label>Color<input disabled value={identity.color}/></label><label>No. lote<input value={lote} onChange={e=>setLote(e.target.value)}/></label><label>Máquina<input value={maquina} onChange={e=>setMaquina(e.target.value)}/></label><label>Molde<input value={molde} onChange={e=>setMolde(e.target.value)}/></label><label>Cavidades<input type="number" min="1" value={cav} onChange={e=>setCav(Number(e.target.value))}/></label><label>Cantidad producción<input type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label>% Virgen<input type="number" min="0" max="100" value={virgen} onChange={e=>setVirgen(Math.max(0,Math.min(100,Number(e.target.value))))}/></label><label>% Molido<input disabled value={100-virgen}/></label></div>
 {spec?<><div className="sampling"><b>Especificación · {identity.familia}</b><span>{spec.nominal} mm nominal</span><span>{spec.ancho} × {spec.espesor} mm</span><span>Fuerza mín. {spec.n.toFixed(2)} N</span></div><div className="sampling"><b>Plan {sp.codigo}</b><span>Muestra {sp.muestra}</span><span>{sp.bolsas}</span><span>Ac {sp.aceptar}</span><span>Re {sp.rechazar}</span></div></>:<div className="alert">La clave no corresponde todavía a una familia ACT/ACN 100, 140, 180, 200, 300 o 370.</div>}
 <div className="quality-form-grid"><label>Operadores<select multiple value={ops} onChange={e=>setOps(Array.from(e.currentTarget.selectedOptions).map(x=>x.value))}>{initialPersonnel().map(x=><option key={x.numero} value={`${x.numero} ${x.nombre}`}>{x.numero} · {x.nombre}</option>)}</select></label><label>Coordinador<select value={coord} onChange={e=>setCoord(e.target.value)}><option value="">Seleccionar</option>{initialPersonnel().filter(x=>x.puesto.toLowerCase().includes('coordinador')).map(x=><option key={x.numero} value={`${x.numero} ${x.nombre}`}>{x.nombre}</option>)}</select></label></div><button className="btn" onClick={create} disabled={!producto||!lote||!molde||!spec}>Iniciar estudio de tensión</button></section>
 {current&&<section className="section"><div className="section-title-row"><div><h2>🧪 Captura rápida · {current.folio}</h2><div className="muted">{current.productoVercel} · {current.destino} · {current.lote}</div></div><button className="btn secondary" onClick={()=>pdf(current)}>Descargar PDF</button></div><div className="grid quality-kpis"><div className="card"><div className="muted">Muestras</div><div className="kpi">{samples.length}/{current.tamanoMuestra}</div></div><div className="card"><div className="muted">Cumplen</div><div className="kpi green">{samples.length-failures}</div></div><div className="card"><div className="muted">No cumplen</div><div className="kpi red">{failures}</div></div><div className="card"><div className="muted">Promedio</div><div className="kpi">{average?average.toFixed(1):'—'} N</div></div></div>
 {current.estado==='EN CAPTURA'?<><div className="quality-form-grid"><label>N° muestra<input disabled value={samples.length+1}/></label><label>Fuerza medida (N)<input autoFocus type="number" step="0.01" value={force} onChange={e=>setForce(e.target.value)}/></label>{Number(force)>0&&Number(force)<current.fuerzaMinN&&<label>Cavidad que falló<select value={failCavity} onChange={e=>setFailCavity(Number(e.target.value))}>{Array.from({length:current.cavidades},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label>}<label>Observación<input value={sampleObs} onChange={e=>setSampleObs(e.target.value)} placeholder="Opcional"/></label></div><button className="btn" onClick={addSample} disabled={!force}>Guardar muestra y continuar</button><p className="muted">La cavidad solo se solicita cuando la fuerza NO CUMPLE, igual que en el flujo anterior.</p></>:<div className="empty-state"><b>✓</b><span>Estudio terminado. Puedes descargar el PDF o consultarlo en historial.</span></div>}
 <div className="table-wrap"><table><thead><tr><th>#</th><th>Fuerza N</th><th>Resultado</th><th>Cavidad falla</th><th>Observación</th></tr></thead><tbody>{samples.slice().reverse().slice(0,15).map(s=><tr key={s.numero}><td>{s.numero}</td><td>{s.fuerzaN.toFixed(2)}</td><td><span className={'result-pill '+(s.resultado==='PASA'?'cumplida':'no-cumplida')}>{s.resultado}</span></td><td>{s.cavidad||'—'}</td><td>{s.observaciones||'—'}</td></tr>)}</tbody></table></div></section>}
 <section className="section"><h2>Historial / continuar estudios</h2><div className="table-wrap"><table><thead><tr><th>Folio</th><th>Clave Vercel</th><th>Destino</th><th>Lote</th><th>Máquina</th><th>Molde</th><th>Avance</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.folio}</td><td>{r.productoVercel||r.producto}</td><td>{r.destino||'—'}</td><td>{r.lote}</td><td>{r.maquina}</td><td>{r.molde}</td><td>{r.muestras.length}/{r.tamanoMuestra||samplingPlan(r.cantidad).muestra}</td><td>{r.estado}</td><td><button className="view-btn" onClick={()=>setActive(r.id)}>{r.estado==='EN CAPTURA'?'Continuar':'Ver'}</button> <button className="view-btn" onClick={()=>pdf(r)}>PDF</button></td></tr>)}</tbody></table></div></section></>;
}
