'use client';
import {useEffect,useMemo,useState} from 'react';
import {Allocation,KEYS,Order,Program,read,scheduleAllocations} from '@/lib/operations';
import {QUALITY_KEYS,QualityRelease,qread} from '@/lib/quality';
import {machineMaster} from '@/lib/machines';
export default function Page(){
 const [programs,setPrograms]=useState<Program[]>([]),[orders,setOrders]=useState<Order[]>([]),[allocs,setAllocs]=useState<Allocation[]>([]),[rels,setRels]=useState<QualityRelease[]>([]),[pid,setPid]=useState('');
 const load=()=>{const ps=read<Program[]>(KEYS.programs,[]);setPrograms(ps);setOrders(read(KEYS.orders,[]));setAllocs(read(KEYS.allocations,[]));setRels(qread(QUALITY_KEYS.releases,[]));setPid(x=>x||ps.find(p=>p.estado!=='CERRADO')?.id||ps[0]?.id||'')};
 useEffect(()=>{load();addEventListener('anclo-operations-updated',load);return()=>removeEventListener('anclo-operations-updated',load)},[]);
 const program=programs.find(p=>p.id===pid);const opIds=new Set(orders.filter(o=>o.programId===pid).map(o=>o.id));const base=allocs.filter(a=>opIds.has(a.orderId));
 const latestByAllocation=useMemo(()=>{const m=new Map<string,QualityRelease>();for(const r of rels.filter(r=>r.estado!=='ANULADA').sort((a,b)=>b.fecha.localeCompare(a.fecha)))if(!m.has(r.allocationId))m.set(r.allocationId,r);return m},[rels]);
 const effective=base.map(a=>{const r=latestByAllocation.get(a.id);return r?{...a,maquina:r.maquinaReal||a.maquina,molde:r.moldeReal||a.molde}:a});
 const rows=scheduleAllocations(effective,program);const machines=Array.from(new Set(rows.map(r=>r.machine))).sort((a,b)=>a.localeCompare(b,'es',{numeric:true}));
 return <><div className="top"><div><div className="title">Gantt de producción</div><div className="muted">El plan original se conserva. Las liberaciones de Calidad actualizan la máquina/molde real y recalculan la cola vigente.</div></div></div><div className="programbar"><label>Programa <select value={pid} onChange={e=>setPid(e.target.value)}>{programs.map(p=><option key={p.id} value={p.id}>{p.nombre} · {p.estado}</option>)}</select></label></div>
 <section className="section"><div className="table-wrap"><table className="schedule-table"><thead><tr><th>Máquina vigente</th><th>Producto</th><th>OP</th><th>Molde vigente</th><th>Inicio</th><th>Fin estimado</th><th>Duración</th><th>Plan original</th><th>Ejecución / cambio</th></tr></thead><tbody>{rows.map(r=>{const ea=effective.find(a=>a.id===r.allocationId)!,orig=base.find(a=>a.id===r.allocationId)!,o=orders.find(x=>x.id===ea.orderId),qr=latestByAllocation.get(ea.id),changed=!!qr&&((qr.maquinaReal&&qr.maquinaReal!==orig.maquina)||(qr.moldeReal&&qr.moldeReal!==orig.molde));return <tr key={r.allocationId}><td><b>{r.machine}</b><small>{machineMaster.find(m=>m.numero===r.machine)?.modelo||''}</small></td><td>{ea.producto}</td><td>{o?.op||o?.folioInterno||'—'}</td><td>{ea.molde}</td><td>{new Date(r.start).toLocaleString('es-MX')}</td><td>{new Date(r.end).toLocaleString('es-MX')}</td><td>{r.hours.toFixed(2)} h</td><td>{orig.maquina} · {orig.molde}</td><td>{changed?<span className="status warn">REPROGRAMADA → {qr?.maquinaReal} · {qr?.moldeReal}</span>:qr?<span className="status ok">EJECUCIÓN CONFIRMADA</span>:<span className="status neutral">SEGÚN PLAN</span>}</td></tr>})}</tbody></table>{rows.length===0&&<div className="empty-state">No hay partidas programadas para este programa.</div>}</div></section>
 <section className="section"><h2>Máquinas con carga vigente</h2><div className="actions">{machines.map(m=><span className="status neutral" key={m}>{m} · {rows.filter(r=>r.machine===m).length} partida(s)</span>)}</div></section></>}
