'use client';
import {useEffect,useMemo,useState} from 'react';
import {Allocation,KEYS,Order,Production,Program,read} from '@/lib/operations';
export default function Page(){
 const [programs,setPrograms]=useState<Program[]>([]),[orders,setOrders]=useState<Order[]>([]),[allocs,setAllocs]=useState<Allocation[]>([]),[prod,setProd]=useState<Production[]>([]),[pid,setPid]=useState('');
 const load=()=>{const ps=read<Program[]>(KEYS.programs,[]);setPrograms(ps);setOrders(read(KEYS.orders,[]));setAllocs(read(KEYS.allocations,[]));setProd(read(KEYS.production,[]));setPid(p=>p||ps[0]?.id||'')};
 useEffect(()=>{load();window.addEventListener('anclo-operations-updated',load);return()=>window.removeEventListener('anclo-operations-updated',load)},[]);
 const po=orders.filter(o=>o.programId===pid);
 const stats=useMemo(()=>{let proceso=0,terminadas=0,bloqueadas=0;for(const o of po){const oa=allocs.filter(a=>a.orderId===o.id),ids=new Set(oa.map(a=>a.id)),rows=prod.filter(p=>ids.has(p.allocationId)),made=rows.reduce((n,r)=>n+(r.piezas||0),0),blocked=rows.some(r=>r.resultado==='NO PRODUJO');if(blocked)bloqueadas++;if((o.cantidad||0)>0&&made>=(o.cantidad||0))terminadas++;else if(made>0)proceso++;}return {total:po.length,proceso,terminadas,bloqueadas}},[po,allocs,prod]);
 return <><div className="top"><div><div className="title">KPIs / Informes</div><div className="muted">Indicadores calculados exclusivamente con la operación registrada</div></div></div><div className="programbar"><select value={pid} onChange={e=>setPid(e.target.value)}><option value="">Seleccionar programa…</option>{programs.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></div><div className="grid"><div className="card"><div className="muted">Órdenes del programa</div><div className="kpi">{stats.total}</div></div><div className="card"><div className="muted">En proceso</div><div className="kpi green">{stats.proceso}</div></div><div className="card"><div className="muted">Terminadas por cantidad</div><div className="kpi">{stats.terminadas}</div></div><div className="card"><div className="muted">Con no-producción / incidencia</div><div className="kpi red">{stats.bloqueadas}</div></div></div>{!pid&&<div className="empty-state"><b>Sin programa seleccionado</b><span>Los KPIs no muestran datos ficticios. Crea o selecciona un programa en Planeación.</span></div>}<div className="section two"><div className="card"><h2>KPIs vinculados</h2><p>Los contadores superiores ya leen Programa → Orden/Folio ANCLO → Partidas → Producción real. Conforme registres producción, los estados cambian automáticamente.</p></div><div className="card"><h2>OEE</h2><p>Se habilitará únicamente cuando existan tiempo programado, paros, ciclo estándar y clasificación de piezas buenas/rechazadas suficientes para calcularlo correctamente.</p></div></div></>}
